/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Family } from './family';
import { NestedRIR } from './nested-rir';
import { NestedTag } from './nested-tag';
import { NestedTenant } from './nested-tenant';

/**
 * 
 * @export
 * @interface Aggregate
 */
export interface Aggregate {
    /**
     * 
     * @type {number}
     * @memberof Aggregate
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Aggregate
     */
    url?: string;
    /**
     * 
     * @type {Family}
     * @memberof Aggregate
     */
    family?: Family;
    /**
     * 
     * @type {string}
     * @memberof Aggregate
     */
    prefix: string;
    /**
     * 
     * @type {NestedRIR}
     * @memberof Aggregate
     */
    rir: NestedRIR;
    /**
     * 
     * @type {NestedTenant}
     * @memberof Aggregate
     */
    tenant?: NestedTenant | null;
    /**
     * 
     * @type {string}
     * @memberof Aggregate
     */
    date_added?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Aggregate
     */
    description?: string;
    /**
     * 
     * @type {Array<NestedTag>}
     * @memberof Aggregate
     */
    tags?: Array<NestedTag>;
    /**
     * 
     * @type {object}
     * @memberof Aggregate
     */
    custom_fields?: object;
    /**
     * 
     * @type {string}
     * @memberof Aggregate
     */
    created?: string;
    /**
     * 
     * @type {string}
     * @memberof Aggregate
     */
    last_updated?: string;
}


