/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { LengthUnit } from './length-unit';
import { NestedTag } from './nested-tag';
import { Status1 } from './status1';

/**
 * 
 * @export
 * @interface Cable
 */
export interface Cable {
    /**
     * 
     * @type {number}
     * @memberof Cable
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Cable
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof Cable
     */
    termination_a_type: string;
    /**
     * 
     * @type {number}
     * @memberof Cable
     */
    termination_a_id: number;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof Cable
     */
    termination_a?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof Cable
     */
    termination_b_type: string;
    /**
     * 
     * @type {number}
     * @memberof Cable
     */
    termination_b_id: number;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof Cable
     */
    termination_b?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof Cable
     */
    type?: CableTypeEnum;
    /**
     * 
     * @type {Status1}
     * @memberof Cable
     */
    status?: Status1;
    /**
     * 
     * @type {string}
     * @memberof Cable
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof Cable
     */
    color?: string;
    /**
     * 
     * @type {number}
     * @memberof Cable
     */
    length?: number | null;
    /**
     * 
     * @type {LengthUnit}
     * @memberof Cable
     */
    length_unit?: LengthUnit;
    /**
     * 
     * @type {Array<NestedTag>}
     * @memberof Cable
     */
    tags?: Array<NestedTag>;
    /**
     * 
     * @type {object}
     * @memberof Cable
     */
    custom_fields?: object;
}

/**
    * @export
    * @enum {string}
    */
export enum CableTypeEnum {
    Cat3 = 'cat3',
    Cat5 = 'cat5',
    Cat5e = 'cat5e',
    Cat6 = 'cat6',
    Cat6a = 'cat6a',
    Cat7 = 'cat7',
    DacActive = 'dac-active',
    DacPassive = 'dac-passive',
    Mrj21Trunk = 'mrj21-trunk',
    Coaxial = 'coaxial',
    Mmf = 'mmf',
    MmfOm1 = 'mmf-om1',
    MmfOm2 = 'mmf-om2',
    MmfOm3 = 'mmf-om3',
    MmfOm4 = 'mmf-om4',
    Smf = 'smf',
    SmfOs1 = 'smf-os1',
    SmfOs2 = 'smf-os2',
    Aoc = 'aoc',
    Power = 'power'
}



