/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedInterface } from './nested-interface';
import { NestedSite } from './nested-site';

/**
 * 
 * @export
 * @interface CircuitCircuitTermination
 */
export interface CircuitCircuitTermination {
    /**
     * 
     * @type {number}
     * @memberof CircuitCircuitTermination
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CircuitCircuitTermination
     */
    url?: string;
    /**
     * 
     * @type {NestedSite}
     * @memberof CircuitCircuitTermination
     */
    site: NestedSite;
    /**
     * 
     * @type {NestedInterface}
     * @memberof CircuitCircuitTermination
     */
    connected_endpoint: NestedInterface;
    /**
     * 
     * @type {number}
     * @memberof CircuitCircuitTermination
     */
    port_speed?: number | null;
    /**
     * Upstream speed, if different from port speed
     * @type {number}
     * @memberof CircuitCircuitTermination
     */
    upstream_speed?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CircuitCircuitTermination
     */
    xconnect_id?: string;
}


