/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CircuitType
 */
export interface CircuitType {
    /**
     * 
     * @type {number}
     * @memberof CircuitType
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CircuitType
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof CircuitType
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CircuitType
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof CircuitType
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof CircuitType
     */
    circuit_count?: number;
}


