/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedClusterGroup } from './nested-cluster-group';
import { NestedClusterType } from './nested-cluster-type';
import { NestedSite } from './nested-site';
import { NestedTag } from './nested-tag';
import { NestedTenant } from './nested-tenant';

/**
 * 
 * @export
 * @interface Cluster
 */
export interface Cluster {
    /**
     * 
     * @type {number}
     * @memberof Cluster
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Cluster
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof Cluster
     */
    name: string;
    /**
     * 
     * @type {NestedClusterType}
     * @memberof Cluster
     */
    type: NestedClusterType;
    /**
     * 
     * @type {NestedClusterGroup}
     * @memberof Cluster
     */
    group?: NestedClusterGroup;
    /**
     * 
     * @type {NestedTenant}
     * @memberof Cluster
     */
    tenant?: NestedTenant | null;
    /**
     * 
     * @type {NestedSite}
     * @memberof Cluster
     */
    site?: NestedSite;
    /**
     * 
     * @type {string}
     * @memberof Cluster
     */
    comments?: string;
    /**
     * 
     * @type {Array<NestedTag>}
     * @memberof Cluster
     */
    tags?: Array<NestedTag>;
    /**
     * 
     * @type {object}
     * @memberof Cluster
     */
    custom_fields?: object;
    /**
     * 
     * @type {string}
     * @memberof Cluster
     */
    created?: string;
    /**
     * 
     * @type {string}
     * @memberof Cluster
     */
    last_updated?: string;
    /**
     * 
     * @type {number}
     * @memberof Cluster
     */
    device_count?: number;
    /**
     * 
     * @type {number}
     * @memberof Cluster
     */
    virtualmachine_count?: number;
}


