/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedDeviceType } from './nested-device-type';
import { Type } from './type';

/**
 * 
 * @export
 * @interface ConsoleServerPortTemplate
 */
export interface ConsoleServerPortTemplate {
    /**
     * 
     * @type {number}
     * @memberof ConsoleServerPortTemplate
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ConsoleServerPortTemplate
     */
    url?: string;
    /**
     * 
     * @type {NestedDeviceType}
     * @memberof ConsoleServerPortTemplate
     */
    device_type: NestedDeviceType;
    /**
     * 
     * @type {string}
     * @memberof ConsoleServerPortTemplate
     */
    name: string;
    /**
     * Physical label
     * @type {string}
     * @memberof ConsoleServerPortTemplate
     */
    label?: string;
    /**
     * 
     * @type {Type}
     * @memberof ConsoleServerPortTemplate
     */
    type?: Type;
    /**
     * 
     * @type {string}
     * @memberof ConsoleServerPortTemplate
     */
    description?: string;
}


