/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedCable } from './nested-cable';
import { NestedDevice } from './nested-device';
import { NestedTag } from './nested-tag';
import { Type } from './type';

/**
 * 
 * @export
 * @interface ConsolePort
 */
export interface ConsolePort {
    /**
     * 
     * @type {number}
     * @memberof ConsolePort
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ConsolePort
     */
    url?: string;
    /**
     * 
     * @type {NestedDevice}
     * @memberof ConsolePort
     */
    device: NestedDevice;
    /**
     * 
     * @type {string}
     * @memberof ConsolePort
     */
    name: string;
    /**
     * Physical label
     * @type {string}
     * @memberof ConsolePort
     */
    label?: string;
    /**
     * 
     * @type {Type}
     * @memberof ConsolePort
     */
    type?: Type;
    /**
     * 
     * @type {string}
     * @memberof ConsolePort
     */
    description?: string;
    /**
     * 
     * @type {NestedCable}
     * @memberof ConsolePort
     */
    cable?: NestedCable;
    /**
     *  Return the appropriate serializer for the cable termination model. 
     * @type {{ [key: string]: string; }}
     * @memberof ConsolePort
     */
    cable_peer?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof ConsolePort
     */
    cable_peer_type?: string;
    /**
     *  Return the appropriate serializer for the type of connected object. 
     * @type {{ [key: string]: string; }}
     * @memberof ConsolePort
     */
    connected_endpoint?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof ConsolePort
     */
    connected_endpoint_type?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ConsolePort
     */
    connected_endpoint_reachable?: boolean;
    /**
     * 
     * @type {Array<NestedTag>}
     * @memberof ConsolePort
     */
    tags?: Array<NestedTag>;
}


