/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Face } from './face';
import { NestedCluster } from './nested-cluster';
import { NestedDevice } from './nested-device';
import { NestedDeviceRole } from './nested-device-role';
import { NestedDeviceType } from './nested-device-type';
import { NestedIPAddress } from './nested-ipaddress';
import { NestedPlatform } from './nested-platform';
import { NestedRack } from './nested-rack';
import { NestedSite } from './nested-site';
import { NestedTag } from './nested-tag';
import { NestedTenant } from './nested-tenant';
import { NestedVirtualChassis } from './nested-virtual-chassis';
import { Status2 } from './status2';

/**
 * 
 * @export
 * @interface Device
 */
export interface Device {
    /**
     * 
     * @type {number}
     * @memberof Device
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    display_name?: string;
    /**
     * 
     * @type {NestedDeviceType}
     * @memberof Device
     */
    device_type: NestedDeviceType;
    /**
     * 
     * @type {NestedDeviceRole}
     * @memberof Device
     */
    device_role: NestedDeviceRole;
    /**
     * 
     * @type {NestedTenant}
     * @memberof Device
     */
    tenant?: NestedTenant | null;
    /**
     * 
     * @type {NestedPlatform}
     * @memberof Device
     */
    platform?: NestedPlatform | null;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    serial?: string;
    /**
     * A unique tag used to identify this device
     * @type {string}
     * @memberof Device
     */
    asset_tag?: string | null;
    /**
     * 
     * @type {NestedSite}
     * @memberof Device
     */
    site: NestedSite;
    /**
     * 
     * @type {NestedRack}
     * @memberof Device
     */
    rack?: NestedRack | null;
    /**
     * The lowest-numbered unit occupied by the device
     * @type {number}
     * @memberof Device
     */
    position?: number | null;
    /**
     * 
     * @type {Face}
     * @memberof Device
     */
    face?: Face;
    /**
     * 
     * @type {NestedDevice}
     * @memberof Device
     */
    parent_device?: NestedDevice;
    /**
     * 
     * @type {Status2}
     * @memberof Device
     */
    status?: Status2;
    /**
     * 
     * @type {NestedIPAddress}
     * @memberof Device
     */
    primary_ip?: NestedIPAddress;
    /**
     * 
     * @type {NestedIPAddress}
     * @memberof Device
     */
    primary_ip4?: NestedIPAddress;
    /**
     * 
     * @type {NestedIPAddress}
     * @memberof Device
     */
    primary_ip6?: NestedIPAddress;
    /**
     * 
     * @type {NestedCluster}
     * @memberof Device
     */
    cluster?: NestedCluster | null;
    /**
     * 
     * @type {NestedVirtualChassis}
     * @memberof Device
     */
    virtual_chassis?: NestedVirtualChassis | null;
    /**
     * 
     * @type {number}
     * @memberof Device
     */
    vc_position?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Device
     */
    vc_priority?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    comments?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    local_context_data?: string | null;
    /**
     * 
     * @type {Array<NestedTag>}
     * @memberof Device
     */
    tags?: Array<NestedTag>;
    /**
     * 
     * @type {object}
     * @memberof Device
     */
    custom_fields?: object;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    created?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    last_updated?: string;
}


