/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedManufacturer } from './nested-manufacturer';
import { NestedTag } from './nested-tag';
import { SubdeviceRole } from './subdevice-role';

/**
 * 
 * @export
 * @interface DeviceType
 */
export interface DeviceType {
    /**
     * 
     * @type {number}
     * @memberof DeviceType
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DeviceType
     */
    url?: string;
    /**
     * 
     * @type {NestedManufacturer}
     * @memberof DeviceType
     */
    manufacturer: NestedManufacturer;
    /**
     * 
     * @type {string}
     * @memberof DeviceType
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceType
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceType
     */
    display_name?: string;
    /**
     * Discrete part number (optional)
     * @type {string}
     * @memberof DeviceType
     */
    part_number?: string;
    /**
     * 
     * @type {number}
     * @memberof DeviceType
     */
    u_height?: number;
    /**
     * Device consumes both front and rear rack faces
     * @type {boolean}
     * @memberof DeviceType
     */
    is_full_depth?: boolean;
    /**
     * 
     * @type {SubdeviceRole}
     * @memberof DeviceType
     */
    subdevice_role?: SubdeviceRole;
    /**
     * 
     * @type {string}
     * @memberof DeviceType
     */
    front_image?: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceType
     */
    rear_image?: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceType
     */
    comments?: string;
    /**
     * 
     * @type {Array<NestedTag>}
     * @memberof DeviceType
     */
    tags?: Array<NestedTag>;
    /**
     * 
     * @type {object}
     * @memberof DeviceType
     */
    custom_fields?: object;
    /**
     * 
     * @type {string}
     * @memberof DeviceType
     */
    created?: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceType
     */
    last_updated?: string;
    /**
     * 
     * @type {number}
     * @memberof DeviceType
     */
    device_count?: number;
}


