/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DeviceRole
 */
export interface DeviceRole {
    /**
     * 
     * @type {number}
     * @memberof DeviceRole
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DeviceRole
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceRole
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceRole
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceRole
     */
    color?: string;
    /**
     * Virtual machines may be assigned to this role
     * @type {boolean}
     * @memberof DeviceRole
     */
    vm_role?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DeviceRole
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof DeviceRole
     */
    device_count?: number;
    /**
     * 
     * @type {number}
     * @memberof DeviceRole
     */
    virtualmachine_count?: number;
}


