/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ExportTemplate
 */
export interface ExportTemplate {
    /**
     * 
     * @type {number}
     * @memberof ExportTemplate
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ExportTemplate
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof ExportTemplate
     */
    content_type: string;
    /**
     * 
     * @type {string}
     * @memberof ExportTemplate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ExportTemplate
     */
    description?: string;
    /**
     * The list of objects being exported is passed as a context variable named <code>queryset</code>.
     * @type {string}
     * @memberof ExportTemplate
     */
    template_code: string;
    /**
     * Defaults to <code>text/plain</code>
     * @type {string}
     * @memberof ExportTemplate
     */
    mime_type?: string;
    /**
     * Extension to append to the rendered filename
     * @type {string}
     * @memberof ExportTemplate
     */
    file_extension?: string;
}


