/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Face
 */
export interface Face {
    /**
     * 
     * @type {string}
     * @memberof Face
     */
    label: FaceLabelEnum;
    /**
     * 
     * @type {string}
     * @memberof Face
     */
    value: FaceValueEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum FaceLabelEnum {
    Front = 'Front',
    Rear = 'Rear'
}
/**
    * @export
    * @enum {string}
    */
export enum FaceValueEnum {
    Front = 'front',
    Rear = 'rear'
}



