/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Family
 */
export interface Family {
    /**
     * 
     * @type {string}
     * @memberof Family
     */
    label: FamilyLabelEnum;
    /**
     * 
     * @type {number}
     * @memberof Family
     */
    value: number;
}

/**
    * @export
    * @enum {string}
    */
export enum FamilyLabelEnum {
    Ipv4 = 'IPv4',
    Ipv6 = 'IPv6'
}



