/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FeedLeg
 */
export interface FeedLeg {
    /**
     * 
     * @type {string}
     * @memberof FeedLeg
     */
    label: FeedLegLabelEnum;
    /**
     * 
     * @type {string}
     * @memberof FeedLeg
     */
    value: FeedLegValueEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum FeedLegLabelEnum {
    A = 'A',
    B = 'B',
    C = 'C'
}
/**
    * @export
    * @enum {string}
    */
export enum FeedLegValueEnum {
    A = 'A',
    B = 'B',
    C = 'C'
}



