/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FilterLogic
 */
export interface FilterLogic {
    /**
     * 
     * @type {string}
     * @memberof FilterLogic
     */
    label: FilterLogicLabelEnum;
    /**
     * 
     * @type {string}
     * @memberof FilterLogic
     */
    value: FilterLogicValueEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum FilterLogicLabelEnum {
    Disabled = 'Disabled',
    Loose = 'Loose',
    Exact = 'Exact'
}
/**
    * @export
    * @enum {string}
    */
export enum FilterLogicValueEnum {
    Disabled = 'disabled',
    Loose = 'loose',
    Exact = 'exact'
}



