/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { VMInterface } from './vminterface';

/**
 * 
 * @export
 * @interface InlineResponse20065
 */
export interface InlineResponse20065 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20065
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20065
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20065
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<VMInterface>}
     * @memberof InlineResponse20065
     */
    results: Array<VMInterface>;
}


