/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Site } from './site';

/**
 * 
 * @export
 * @interface InlineResponse20035
 */
export interface InlineResponse20035 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20035
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20035
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20035
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Site>}
     * @memberof InlineResponse20035
     */
    results: Array<Site>;
}


