/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { VirtualMachineWithConfigContext } from './virtual-machine-with-config-context';

/**
 * 
 * @export
 * @interface InlineResponse20066
 */
export interface InlineResponse20066 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20066
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20066
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20066
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<VirtualMachineWithConfigContext>}
     * @memberof InlineResponse20066
     */
    results: Array<VirtualMachineWithConfigContext>;
}


