/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ObjectPermission } from './object-permission';

/**
 * 
 * @export
 * @interface InlineResponse20060
 */
export interface InlineResponse20060 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20060
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20060
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20060
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<ObjectPermission>}
     * @memberof InlineResponse20060
     */
    results: Array<ObjectPermission>;
}


