/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { SecretRole } from './secret-role';

/**
 * 
 * @export
 * @interface InlineResponse20055
 */
export interface InlineResponse20055 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20055
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20055
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20055
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<SecretRole>}
     * @memberof InlineResponse20055
     */
    results: Array<SecretRole>;
}


