/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { RearPortTemplate } from './rear-port-template';

/**
 * 
 * @export
 * @interface InlineResponse20032
 */
export interface InlineResponse20032 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20032
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20032
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20032
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<RearPortTemplate>}
     * @memberof InlineResponse20032
     */
    results: Array<RearPortTemplate>;
}


