/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { PowerPortTemplate } from './power-port-template';

/**
 * 
 * @export
 * @interface InlineResponse20027
 */
export interface InlineResponse20027 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20027
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20027
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20027
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<PowerPortTemplate>}
     * @memberof InlineResponse20027
     */
    results: Array<PowerPortTemplate>;
}


