/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { RackGroup } from './rack-group';

/**
 * 
 * @export
 * @interface InlineResponse20028
 */
export interface InlineResponse20028 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20028
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20028
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20028
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<RackGroup>}
     * @memberof InlineResponse20028
     */
    results: Array<RackGroup>;
}


