/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ContentType } from './content-type';

/**
 * 
 * @export
 * @interface InlineResponse20038
 */
export interface InlineResponse20038 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20038
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20038
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20038
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<ContentType>}
     * @memberof InlineResponse20038
     */
    results: Array<ContentType>;
}


