/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { PowerFeed } from './power-feed';

/**
 * 
 * @export
 * @interface InlineResponse20023
 */
export interface InlineResponse20023 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20023
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20023
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20023
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<PowerFeed>}
     * @memberof InlineResponse20023
     */
    results: Array<PowerFeed>;
}


