/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { PowerPanel } from './power-panel';

/**
 * 
 * @export
 * @interface InlineResponse20026
 */
export interface InlineResponse20026 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20026
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20026
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20026
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<PowerPanel>}
     * @memberof InlineResponse20026
     */
    results: Array<PowerPanel>;
}


