/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { RearPort } from './rear-port';

/**
 * 
 * @export
 * @interface InlineResponse20033
 */
export interface InlineResponse20033 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20033
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20033
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20033
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<RearPort>}
     * @memberof InlineResponse20033
     */
    results: Array<RearPort>;
}


