/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { RouteTarget } from './route-target';

/**
 * 
 * @export
 * @interface InlineResponse20050
 */
export interface InlineResponse20050 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20050
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20050
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20050
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<RouteTarget>}
     * @memberof InlineResponse20050
     */
    results: Array<RouteTarget>;
}


