/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ObjectChange } from './object-change';

/**
 * 
 * @export
 * @interface InlineResponse20043
 */
export interface InlineResponse20043 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20043
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20043
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20043
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<ObjectChange>}
     * @memberof InlineResponse20043
     */
    results: Array<ObjectChange>;
}


