/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Secret } from './secret';

/**
 * 
 * @export
 * @interface InlineResponse20056
 */
export interface InlineResponse20056 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20056
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20056
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20056
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Secret>}
     * @memberof InlineResponse20056
     */
    results: Array<Secret>;
}


