/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { RackReservation } from './rack-reservation';

/**
 * 
 * @export
 * @interface InlineResponse20029
 */
export interface InlineResponse20029 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20029
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20029
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20029
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<RackReservation>}
     * @memberof InlineResponse20029
     */
    results: Array<RackReservation>;
}


