/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Mode } from './mode';
import { NestedCable } from './nested-cable';
import { NestedDevice } from './nested-device';
import { NestedInterface } from './nested-interface';
import { NestedTag } from './nested-tag';
import { NestedVLAN } from './nested-vlan';
import { Type2 } from './type2';

/**
 * 
 * @export
 * @interface Interface
 */
export interface Interface {
    /**
     * 
     * @type {number}
     * @memberof Interface
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Interface
     */
    url?: string;
    /**
     * 
     * @type {NestedDevice}
     * @memberof Interface
     */
    device: NestedDevice;
    /**
     * 
     * @type {string}
     * @memberof Interface
     */
    name: string;
    /**
     * Physical label
     * @type {string}
     * @memberof Interface
     */
    label?: string;
    /**
     * 
     * @type {Type2}
     * @memberof Interface
     */
    type: Type2;
    /**
     * 
     * @type {boolean}
     * @memberof Interface
     */
    enabled?: boolean;
    /**
     * 
     * @type {NestedInterface}
     * @memberof Interface
     */
    lag?: NestedInterface;
    /**
     * 
     * @type {number}
     * @memberof Interface
     */
    mtu?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Interface
     */
    mac_address?: string | null;
    /**
     * This interface is used only for out-of-band management
     * @type {boolean}
     * @memberof Interface
     */
    mgmt_only?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Interface
     */
    description?: string;
    /**
     * 
     * @type {Mode}
     * @memberof Interface
     */
    mode?: Mode;
    /**
     * 
     * @type {NestedVLAN}
     * @memberof Interface
     */
    untagged_vlan?: NestedVLAN | null;
    /**
     * 
     * @type {Set<NestedVLAN>}
     * @memberof Interface
     */
    tagged_vlans?: Set<NestedVLAN>;
    /**
     * 
     * @type {NestedCable}
     * @memberof Interface
     */
    cable?: NestedCable;
    /**
     *  Return the appropriate serializer for the cable termination model. 
     * @type {{ [key: string]: string; }}
     * @memberof Interface
     */
    cable_peer?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof Interface
     */
    cable_peer_type?: string;
    /**
     *  Return the appropriate serializer for the type of connected object. 
     * @type {{ [key: string]: string; }}
     * @memberof Interface
     */
    connected_endpoint?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof Interface
     */
    connected_endpoint_type?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Interface
     */
    connected_endpoint_reachable?: boolean;
    /**
     * 
     * @type {Array<NestedTag>}
     * @memberof Interface
     */
    tags?: Array<NestedTag>;
    /**
     * 
     * @type {number}
     * @memberof Interface
     */
    count_ipaddresses?: number;
}


