/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedDeviceType } from './nested-device-type';
import { Type2 } from './type2';

/**
 * 
 * @export
 * @interface InterfaceTemplate
 */
export interface InterfaceTemplate {
    /**
     * 
     * @type {number}
     * @memberof InterfaceTemplate
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof InterfaceTemplate
     */
    url?: string;
    /**
     * 
     * @type {NestedDeviceType}
     * @memberof InterfaceTemplate
     */
    device_type: NestedDeviceType;
    /**
     * 
     * @type {string}
     * @memberof InterfaceTemplate
     */
    name: string;
    /**
     * Physical label
     * @type {string}
     * @memberof InterfaceTemplate
     */
    label?: string;
    /**
     * 
     * @type {Type2}
     * @memberof InterfaceTemplate
     */
    type: Type2;
    /**
     * 
     * @type {boolean}
     * @memberof InterfaceTemplate
     */
    mgmt_only?: boolean;
    /**
     * 
     * @type {string}
     * @memberof InterfaceTemplate
     */
    description?: string;
}


