/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedInterface } from './nested-interface';

/**
 * 
 * @export
 * @interface InterfaceConnection
 */
export interface InterfaceConnection {
    /**
     * 
     * @type {NestedInterface}
     * @memberof InterfaceConnection
     */
    interface_a?: NestedInterface;
    /**
     * 
     * @type {NestedInterface}
     * @memberof InterfaceConnection
     */
    interface_b: NestedInterface;
    /**
     * 
     * @type {boolean}
     * @memberof InterfaceConnection
     */
    connected_endpoint_reachable?: boolean;
}


