/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedDevice } from './nested-device';
import { NestedManufacturer } from './nested-manufacturer';
import { NestedTag } from './nested-tag';

/**
 * 
 * @export
 * @interface InventoryItem
 */
export interface InventoryItem {
    /**
     * 
     * @type {number}
     * @memberof InventoryItem
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof InventoryItem
     */
    url?: string;
    /**
     * 
     * @type {NestedDevice}
     * @memberof InventoryItem
     */
    device: NestedDevice;
    /**
     * 
     * @type {number}
     * @memberof InventoryItem
     */
    parent?: number | null;
    /**
     * 
     * @type {string}
     * @memberof InventoryItem
     */
    name: string;
    /**
     * Physical label
     * @type {string}
     * @memberof InventoryItem
     */
    label?: string;
    /**
     * 
     * @type {NestedManufacturer}
     * @memberof InventoryItem
     */
    manufacturer?: NestedManufacturer;
    /**
     * Manufacturer-assigned part identifier
     * @type {string}
     * @memberof InventoryItem
     */
    part_id?: string;
    /**
     * 
     * @type {string}
     * @memberof InventoryItem
     */
    serial?: string;
    /**
     * A unique tag used to identify this item
     * @type {string}
     * @memberof InventoryItem
     */
    asset_tag?: string | null;
    /**
     * This item was automatically discovered
     * @type {boolean}
     * @memberof InventoryItem
     */
    discovered?: boolean;
    /**
     * 
     * @type {string}
     * @memberof InventoryItem
     */
    description?: string;
    /**
     * 
     * @type {Array<NestedTag>}
     * @memberof InventoryItem
     */
    tags?: Array<NestedTag>;
    /**
     * 
     * @type {number}
     * @memberof InventoryItem
     */
    _depth?: number;
}


