/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Family } from './family';
import { NestedIPAddress } from './nested-ipaddress';
import { NestedTag } from './nested-tag';
import { NestedTenant } from './nested-tenant';
import { NestedVRF } from './nested-vrf';
import { Role1 } from './role1';
import { Status7 } from './status7';

/**
 * 
 * @export
 * @interface IPAddress
 */
export interface IPAddress {
    /**
     * 
     * @type {number}
     * @memberof IPAddress
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof IPAddress
     */
    url?: string;
    /**
     * 
     * @type {Family}
     * @memberof IPAddress
     */
    family?: Family;
    /**
     * IPv4 or IPv6 address (with mask)
     * @type {string}
     * @memberof IPAddress
     */
    address: string;
    /**
     * 
     * @type {NestedVRF}
     * @memberof IPAddress
     */
    vrf?: NestedVRF | null;
    /**
     * 
     * @type {NestedTenant}
     * @memberof IPAddress
     */
    tenant?: NestedTenant | null;
    /**
     * 
     * @type {Status7}
     * @memberof IPAddress
     */
    status?: Status7;
    /**
     * 
     * @type {Role1}
     * @memberof IPAddress
     */
    role?: Role1;
    /**
     * 
     * @type {string}
     * @memberof IPAddress
     */
    assigned_object_type?: string | null;
    /**
     * 
     * @type {number}
     * @memberof IPAddress
     */
    assigned_object_id?: number | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof IPAddress
     */
    assigned_object?: { [key: string]: string; };
    /**
     * 
     * @type {NestedIPAddress}
     * @memberof IPAddress
     */
    nat_inside?: NestedIPAddress;
    /**
     * 
     * @type {NestedIPAddress}
     * @memberof IPAddress
     */
    nat_outside?: NestedIPAddress;
    /**
     * Hostname or FQDN (not case-sensitive)
     * @type {string}
     * @memberof IPAddress
     */
    dns_name?: string;
    /**
     * 
     * @type {string}
     * @memberof IPAddress
     */
    description?: string;
    /**
     * 
     * @type {Array<NestedTag>}
     * @memberof IPAddress
     */
    tags?: Array<NestedTag>;
    /**
     * 
     * @type {object}
     * @memberof IPAddress
     */
    custom_fields?: object;
    /**
     * 
     * @type {string}
     * @memberof IPAddress
     */
    created?: string;
    /**
     * 
     * @type {string}
     * @memberof IPAddress
     */
    last_updated?: string;
}


