/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LengthUnit
 */
export interface LengthUnit {
    /**
     * 
     * @type {string}
     * @memberof LengthUnit
     */
    label: LengthUnitLabelEnum;
    /**
     * 
     * @type {string}
     * @memberof LengthUnit
     */
    value: LengthUnitValueEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum LengthUnitLabelEnum {
    Meters = 'Meters',
    Centimeters = 'Centimeters',
    Feet = 'Feet',
    Inches = 'Inches'
}
/**
    * @export
    * @enum {string}
    */
export enum LengthUnitValueEnum {
    M = 'm',
    Cm = 'cm',
    Ft = 'ft',
    In = 'in'
}



