/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NestedVRF
 */
export interface NestedVRF {
    /**
     * 
     * @type {number}
     * @memberof NestedVRF
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof NestedVRF
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof NestedVRF
     */
    name: string;
    /**
     * Unique route distinguisher (as defined in RFC 4364)
     * @type {string}
     * @memberof NestedVRF
     */
    rd?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NestedVRF
     */
    display_name?: string;
    /**
     * 
     * @type {number}
     * @memberof NestedVRF
     */
    prefix_count?: number;
}


