/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedDevice } from './nested-device';

/**
 * 
 * @export
 * @interface NestedPowerPort
 */
export interface NestedPowerPort {
    /**
     * 
     * @type {number}
     * @memberof NestedPowerPort
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof NestedPowerPort
     */
    url?: string;
    /**
     * 
     * @type {NestedDevice}
     * @memberof NestedPowerPort
     */
    device?: NestedDevice;
    /**
     * 
     * @type {string}
     * @memberof NestedPowerPort
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof NestedPowerPort
     */
    cable?: number | null;
}


