/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NestedUser
 */
export interface NestedUser {
    /**
     * 
     * @type {number}
     * @memberof NestedUser
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof NestedUser
     */
    url?: string;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof NestedUser
     */
    username: string;
}


