/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NestedIPAddress
 */
export interface NestedIPAddress {
    /**
     * 
     * @type {number}
     * @memberof NestedIPAddress
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof NestedIPAddress
     */
    url?: string;
    /**
     * 
     * @type {number}
     * @memberof NestedIPAddress
     */
    family?: number;
    /**
     * IPv4 or IPv6 address (with mask)
     * @type {string}
     * @memberof NestedIPAddress
     */
    address: string;
}


