/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedManufacturer } from './nested-manufacturer';

/**
 * 
 * @export
 * @interface NestedDeviceType
 */
export interface NestedDeviceType {
    /**
     * 
     * @type {number}
     * @memberof NestedDeviceType
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof NestedDeviceType
     */
    url?: string;
    /**
     * 
     * @type {NestedManufacturer}
     * @memberof NestedDeviceType
     */
    manufacturer?: NestedManufacturer;
    /**
     * 
     * @type {string}
     * @memberof NestedDeviceType
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof NestedDeviceType
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof NestedDeviceType
     */
    display_name?: string;
    /**
     * 
     * @type {number}
     * @memberof NestedDeviceType
     */
    device_count?: number;
}


