/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NestedVLAN
 */
export interface NestedVLAN {
    /**
     * 
     * @type {number}
     * @memberof NestedVLAN
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof NestedVLAN
     */
    url?: string;
    /**
     * 
     * @type {number}
     * @memberof NestedVLAN
     */
    vid: number;
    /**
     * 
     * @type {string}
     * @memberof NestedVLAN
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof NestedVLAN
     */
    display_name?: string;
}


