/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OuterUnit
 */
export interface OuterUnit {
    /**
     * 
     * @type {string}
     * @memberof OuterUnit
     */
    label: OuterUnitLabelEnum;
    /**
     * 
     * @type {string}
     * @memberof OuterUnit
     */
    value: OuterUnitValueEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum OuterUnitLabelEnum {
    Millimeters = 'Millimeters',
    Inches = 'Inches'
}
/**
    * @export
    * @enum {string}
    */
export enum OuterUnitValueEnum {
    Mm = 'mm',
    In = 'in'
}



