/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Phase
 */
export interface Phase {
    /**
     * 
     * @type {string}
     * @memberof Phase
     */
    label: PhaseLabelEnum;
    /**
     * 
     * @type {string}
     * @memberof Phase
     */
    value: PhaseValueEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum PhaseLabelEnum {
    SinglePhase = 'Single phase',
    ThreePhase = 'Three-phase'
}
/**
    * @export
    * @enum {string}
    */
export enum PhaseValueEnum {
    SinglePhase = 'single-phase',
    ThreePhase = 'three-phase'
}



