/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedManufacturer } from './nested-manufacturer';

/**
 * 
 * @export
 * @interface Platform
 */
export interface Platform {
    /**
     * 
     * @type {number}
     * @memberof Platform
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Platform
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof Platform
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Platform
     */
    slug: string;
    /**
     * 
     * @type {NestedManufacturer}
     * @memberof Platform
     */
    manufacturer?: NestedManufacturer;
    /**
     * The name of the NAPALM driver to use when interacting with devices
     * @type {string}
     * @memberof Platform
     */
    napalm_driver?: string;
    /**
     * Additional arguments to pass when initiating the NAPALM driver (JSON format)
     * @type {string}
     * @memberof Platform
     */
    napalm_args?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Platform
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof Platform
     */
    device_count?: number;
    /**
     * 
     * @type {number}
     * @memberof Platform
     */
    virtualmachine_count?: number;
}


