/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedDeviceType } from './nested-device-type';
import { Type3 } from './type3';

/**
 * 
 * @export
 * @interface PowerPortTemplate
 */
export interface PowerPortTemplate {
    /**
     * 
     * @type {number}
     * @memberof PowerPortTemplate
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PowerPortTemplate
     */
    url?: string;
    /**
     * 
     * @type {NestedDeviceType}
     * @memberof PowerPortTemplate
     */
    device_type: NestedDeviceType;
    /**
     * 
     * @type {string}
     * @memberof PowerPortTemplate
     */
    name: string;
    /**
     * Physical label
     * @type {string}
     * @memberof PowerPortTemplate
     */
    label?: string;
    /**
     * 
     * @type {Type3}
     * @memberof PowerPortTemplate
     */
    type?: Type3;
    /**
     * Maximum power draw (watts)
     * @type {number}
     * @memberof PowerPortTemplate
     */
    maximum_draw?: number | null;
    /**
     * Allocated power draw (watts)
     * @type {number}
     * @memberof PowerPortTemplate
     */
    allocated_draw?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PowerPortTemplate
     */
    description?: string;
}


