/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedCable } from './nested-cable';
import { NestedDevice } from './nested-device';
import { NestedTag } from './nested-tag';
import { Type3 } from './type3';

/**
 * 
 * @export
 * @interface PowerPort
 */
export interface PowerPort {
    /**
     * 
     * @type {number}
     * @memberof PowerPort
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PowerPort
     */
    url?: string;
    /**
     * 
     * @type {NestedDevice}
     * @memberof PowerPort
     */
    device: NestedDevice;
    /**
     * 
     * @type {string}
     * @memberof PowerPort
     */
    name: string;
    /**
     * Physical label
     * @type {string}
     * @memberof PowerPort
     */
    label?: string;
    /**
     * 
     * @type {Type3}
     * @memberof PowerPort
     */
    type?: Type3;
    /**
     * Maximum power draw (watts)
     * @type {number}
     * @memberof PowerPort
     */
    maximum_draw?: number | null;
    /**
     * Allocated power draw (watts)
     * @type {number}
     * @memberof PowerPort
     */
    allocated_draw?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PowerPort
     */
    description?: string;
    /**
     * 
     * @type {NestedCable}
     * @memberof PowerPort
     */
    cable?: NestedCable;
    /**
     *  Return the appropriate serializer for the cable termination model. 
     * @type {{ [key: string]: string; }}
     * @memberof PowerPort
     */
    cable_peer?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof PowerPort
     */
    cable_peer_type?: string;
    /**
     *  Return the appropriate serializer for the type of connected object. 
     * @type {{ [key: string]: string; }}
     * @memberof PowerPort
     */
    connected_endpoint?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof PowerPort
     */
    connected_endpoint_type?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PowerPort
     */
    connected_endpoint_reachable?: boolean;
    /**
     * 
     * @type {Array<NestedTag>}
     * @memberof PowerPort
     */
    tags?: Array<NestedTag>;
}


