/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FeedLeg } from './feed-leg';
import { NestedDeviceType } from './nested-device-type';
import { NestedPowerPortTemplate } from './nested-power-port-template';
import { Type5 } from './type5';

/**
 * 
 * @export
 * @interface PowerOutletTemplate
 */
export interface PowerOutletTemplate {
    /**
     * 
     * @type {number}
     * @memberof PowerOutletTemplate
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PowerOutletTemplate
     */
    url?: string;
    /**
     * 
     * @type {NestedDeviceType}
     * @memberof PowerOutletTemplate
     */
    device_type: NestedDeviceType;
    /**
     * 
     * @type {string}
     * @memberof PowerOutletTemplate
     */
    name: string;
    /**
     * Physical label
     * @type {string}
     * @memberof PowerOutletTemplate
     */
    label?: string;
    /**
     * 
     * @type {Type5}
     * @memberof PowerOutletTemplate
     */
    type?: Type5;
    /**
     * 
     * @type {NestedPowerPortTemplate}
     * @memberof PowerOutletTemplate
     */
    power_port?: NestedPowerPortTemplate;
    /**
     * 
     * @type {FeedLeg}
     * @memberof PowerOutletTemplate
     */
    feed_leg?: FeedLeg;
    /**
     * 
     * @type {string}
     * @memberof PowerOutletTemplate
     */
    description?: string;
}


