/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedCable } from './nested-cable';
import { NestedPowerPanel } from './nested-power-panel';
import { NestedRack } from './nested-rack';
import { NestedTag } from './nested-tag';
import { Phase } from './phase';
import { Status3 } from './status3';
import { Supply } from './supply';
import { Type4 } from './type4';

/**
 * 
 * @export
 * @interface PowerFeed
 */
export interface PowerFeed {
    /**
     * 
     * @type {number}
     * @memberof PowerFeed
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PowerFeed
     */
    url?: string;
    /**
     * 
     * @type {NestedPowerPanel}
     * @memberof PowerFeed
     */
    power_panel: NestedPowerPanel;
    /**
     * 
     * @type {NestedRack}
     * @memberof PowerFeed
     */
    rack?: NestedRack | null;
    /**
     * 
     * @type {string}
     * @memberof PowerFeed
     */
    name: string;
    /**
     * 
     * @type {Status3}
     * @memberof PowerFeed
     */
    status?: Status3;
    /**
     * 
     * @type {Type4}
     * @memberof PowerFeed
     */
    type?: Type4;
    /**
     * 
     * @type {Supply}
     * @memberof PowerFeed
     */
    supply?: Supply;
    /**
     * 
     * @type {Phase}
     * @memberof PowerFeed
     */
    phase?: Phase;
    /**
     * 
     * @type {number}
     * @memberof PowerFeed
     */
    voltage?: number;
    /**
     * 
     * @type {number}
     * @memberof PowerFeed
     */
    amperage?: number;
    /**
     * Maximum permissible draw (percentage)
     * @type {number}
     * @memberof PowerFeed
     */
    max_utilization?: number;
    /**
     * 
     * @type {string}
     * @memberof PowerFeed
     */
    comments?: string;
    /**
     * 
     * @type {NestedCable}
     * @memberof PowerFeed
     */
    cable?: NestedCable;
    /**
     *  Return the appropriate serializer for the cable termination model. 
     * @type {{ [key: string]: string; }}
     * @memberof PowerFeed
     */
    cable_peer?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof PowerFeed
     */
    cable_peer_type?: string;
    /**
     *  Return the appropriate serializer for the type of connected object. 
     * @type {{ [key: string]: string; }}
     * @memberof PowerFeed
     */
    connected_endpoint?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof PowerFeed
     */
    connected_endpoint_type?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PowerFeed
     */
    connected_endpoint_reachable?: boolean;
    /**
     * 
     * @type {Array<NestedTag>}
     * @memberof PowerFeed
     */
    tags?: Array<NestedTag>;
    /**
     * 
     * @type {object}
     * @memberof PowerFeed
     */
    custom_fields?: object;
    /**
     * 
     * @type {string}
     * @memberof PowerFeed
     */
    created?: string;
    /**
     * 
     * @type {string}
     * @memberof PowerFeed
     */
    last_updated?: string;
}


