/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Family } from './family';
import { NestedRole } from './nested-role';
import { NestedSite } from './nested-site';
import { NestedTag } from './nested-tag';
import { NestedTenant } from './nested-tenant';
import { NestedVLAN } from './nested-vlan';
import { NestedVRF } from './nested-vrf';
import { Status8 } from './status8';

/**
 * 
 * @export
 * @interface Prefix
 */
export interface Prefix {
    /**
     * 
     * @type {number}
     * @memberof Prefix
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Prefix
     */
    url?: string;
    /**
     * 
     * @type {Family}
     * @memberof Prefix
     */
    family?: Family;
    /**
     * IPv4 or IPv6 network with mask
     * @type {string}
     * @memberof Prefix
     */
    prefix: string;
    /**
     * 
     * @type {NestedSite}
     * @memberof Prefix
     */
    site?: NestedSite;
    /**
     * 
     * @type {NestedVRF}
     * @memberof Prefix
     */
    vrf?: NestedVRF | null;
    /**
     * 
     * @type {NestedTenant}
     * @memberof Prefix
     */
    tenant?: NestedTenant | null;
    /**
     * 
     * @type {NestedVLAN}
     * @memberof Prefix
     */
    vlan?: NestedVLAN | null;
    /**
     * 
     * @type {Status8}
     * @memberof Prefix
     */
    status?: Status8;
    /**
     * 
     * @type {NestedRole}
     * @memberof Prefix
     */
    role?: NestedRole | null;
    /**
     * All IP addresses within this prefix are considered usable
     * @type {boolean}
     * @memberof Prefix
     */
    is_pool?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Prefix
     */
    description?: string;
    /**
     * 
     * @type {Array<NestedTag>}
     * @memberof Prefix
     */
    tags?: Array<NestedTag>;
    /**
     * 
     * @type {object}
     * @memberof Prefix
     */
    custom_fields?: object;
    /**
     * 
     * @type {string}
     * @memberof Prefix
     */
    created?: string;
    /**
     * 
     * @type {string}
     * @memberof Prefix
     */
    last_updated?: string;
}


