/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Protocol
 */
export interface Protocol {
    /**
     * 
     * @type {string}
     * @memberof Protocol
     */
    label: ProtocolLabelEnum;
    /**
     * 
     * @type {string}
     * @memberof Protocol
     */
    value: ProtocolValueEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum ProtocolLabelEnum {
    Tcp = 'TCP',
    Udp = 'UDP'
}
/**
    * @export
    * @enum {string}
    */
export enum ProtocolValueEnum {
    Tcp = 'tcp',
    Udp = 'udp'
}



