/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Face1 } from './face1';
import { NestedDevice } from './nested-device';

/**
 * 
 * @export
 * @interface RackUnit
 */
export interface RackUnit {
    /**
     * 
     * @type {number}
     * @memberof RackUnit
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof RackUnit
     */
    name?: string;
    /**
     * 
     * @type {Face1}
     * @memberof RackUnit
     */
    face?: Face1;
    /**
     * 
     * @type {NestedDevice}
     * @memberof RackUnit
     */
    device?: NestedDevice;
    /**
     * 
     * @type {boolean}
     * @memberof RackUnit
     */
    occupied?: boolean;
}


