/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedRackGroup } from './nested-rack-group';
import { NestedSite } from './nested-site';

/**
 * 
 * @export
 * @interface RackGroup
 */
export interface RackGroup {
    /**
     * 
     * @type {number}
     * @memberof RackGroup
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof RackGroup
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof RackGroup
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RackGroup
     */
    slug: string;
    /**
     * 
     * @type {NestedSite}
     * @memberof RackGroup
     */
    site: NestedSite;
    /**
     * 
     * @type {NestedRackGroup}
     * @memberof RackGroup
     */
    parent?: NestedRackGroup | null;
    /**
     * 
     * @type {string}
     * @memberof RackGroup
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof RackGroup
     */
    rack_count?: number;
    /**
     * 
     * @type {number}
     * @memberof RackGroup
     */
    _depth?: number;
}


