/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedRack } from './nested-rack';
import { NestedTag } from './nested-tag';
import { NestedTenant } from './nested-tenant';
import { NestedUser } from './nested-user';

/**
 * 
 * @export
 * @interface RackReservation
 */
export interface RackReservation {
    /**
     * 
     * @type {number}
     * @memberof RackReservation
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof RackReservation
     */
    url?: string;
    /**
     * 
     * @type {NestedRack}
     * @memberof RackReservation
     */
    rack: NestedRack | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof RackReservation
     */
    units: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof RackReservation
     */
    created?: string;
    /**
     * 
     * @type {NestedUser}
     * @memberof RackReservation
     */
    user: NestedUser;
    /**
     * 
     * @type {NestedTenant}
     * @memberof RackReservation
     */
    tenant?: NestedTenant | null;
    /**
     * 
     * @type {string}
     * @memberof RackReservation
     */
    description: string;
    /**
     * 
     * @type {Array<NestedTag>}
     * @memberof RackReservation
     */
    tags?: Array<NestedTag>;
    /**
     * 
     * @type {object}
     * @memberof RackReservation
     */
    custom_fields?: object;
}


