/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RIR
 */
export interface RIR {
    /**
     * 
     * @type {number}
     * @memberof RIR
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof RIR
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof RIR
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RIR
     */
    slug: string;
    /**
     * IP space managed by this RIR is considered private
     * @type {boolean}
     * @memberof RIR
     */
    is_private?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RIR
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof RIR
     */
    aggregate_count?: number;
}


