/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedTag } from './nested-tag';
import { NestedTenant } from './nested-tenant';

/**
 * 
 * @export
 * @interface RouteTarget
 */
export interface RouteTarget {
    /**
     * 
     * @type {number}
     * @memberof RouteTarget
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof RouteTarget
     */
    url?: string;
    /**
     * Route target value (formatted in accordance with RFC 4360)
     * @type {string}
     * @memberof RouteTarget
     */
    name: string;
    /**
     * 
     * @type {NestedTenant}
     * @memberof RouteTarget
     */
    tenant?: NestedTenant | null;
    /**
     * 
     * @type {string}
     * @memberof RouteTarget
     */
    description?: string;
    /**
     * 
     * @type {Array<NestedTag>}
     * @memberof RouteTarget
     */
    tags?: Array<NestedTag>;
    /**
     * 
     * @type {object}
     * @memberof RouteTarget
     */
    custom_fields?: object;
    /**
     * 
     * @type {string}
     * @memberof RouteTarget
     */
    created?: string;
    /**
     * 
     * @type {string}
     * @memberof RouteTarget
     */
    last_updated?: string;
}


