/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedDevice } from './nested-device';
import { NestedIPAddress } from './nested-ipaddress';
import { NestedTag } from './nested-tag';
import { NestedVirtualMachine } from './nested-virtual-machine';
import { Protocol } from './protocol';

/**
 * 
 * @export
 * @interface Service
 */
export interface Service {
    /**
     * 
     * @type {number}
     * @memberof Service
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Service
     */
    url?: string;
    /**
     * 
     * @type {NestedDevice}
     * @memberof Service
     */
    device?: NestedDevice;
    /**
     * 
     * @type {NestedVirtualMachine}
     * @memberof Service
     */
    virtual_machine?: NestedVirtualMachine | null;
    /**
     * 
     * @type {string}
     * @memberof Service
     */
    name: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof Service
     */
    ports: Array<number>;
    /**
     * 
     * @type {Protocol}
     * @memberof Service
     */
    protocol?: Protocol;
    /**
     * 
     * @type {Set<NestedIPAddress>}
     * @memberof Service
     */
    ipaddresses?: Set<NestedIPAddress>;
    /**
     * 
     * @type {string}
     * @memberof Service
     */
    description?: string;
    /**
     * 
     * @type {Array<NestedTag>}
     * @memberof Service
     */
    tags?: Array<NestedTag>;
    /**
     * 
     * @type {object}
     * @memberof Service
     */
    custom_fields?: object;
    /**
     * 
     * @type {string}
     * @memberof Service
     */
    created?: string;
    /**
     * 
     * @type {string}
     * @memberof Service
     */
    last_updated?: string;
}


