/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedRegion } from './nested-region';
import { NestedTag } from './nested-tag';
import { NestedTenant } from './nested-tenant';
import { Status5 } from './status5';

/**
 * 
 * @export
 * @interface Site
 */
export interface Site {
    /**
     * 
     * @type {number}
     * @memberof Site
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Site
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof Site
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Site
     */
    slug: string;
    /**
     * 
     * @type {Status5}
     * @memberof Site
     */
    status?: Status5;
    /**
     * 
     * @type {NestedRegion}
     * @memberof Site
     */
    region?: NestedRegion | null;
    /**
     * 
     * @type {NestedTenant}
     * @memberof Site
     */
    tenant?: NestedTenant | null;
    /**
     * Local facility ID or description
     * @type {string}
     * @memberof Site
     */
    facility?: string;
    /**
     * 32-bit autonomous system number
     * @type {number}
     * @memberof Site
     */
    asn?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Site
     */
    time_zone?: string;
    /**
     * 
     * @type {string}
     * @memberof Site
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Site
     */
    physical_address?: string;
    /**
     * 
     * @type {string}
     * @memberof Site
     */
    shipping_address?: string;
    /**
     * GPS coordinate (latitude)
     * @type {string}
     * @memberof Site
     */
    latitude?: string | null;
    /**
     * GPS coordinate (longitude)
     * @type {string}
     * @memberof Site
     */
    longitude?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Site
     */
    contact_name?: string;
    /**
     * 
     * @type {string}
     * @memberof Site
     */
    contact_phone?: string;
    /**
     * 
     * @type {string}
     * @memberof Site
     */
    contact_email?: string;
    /**
     * 
     * @type {string}
     * @memberof Site
     */
    comments?: string;
    /**
     * 
     * @type {Array<NestedTag>}
     * @memberof Site
     */
    tags?: Array<NestedTag>;
    /**
     * 
     * @type {object}
     * @memberof Site
     */
    custom_fields?: object;
    /**
     * 
     * @type {string}
     * @memberof Site
     */
    created?: string;
    /**
     * 
     * @type {string}
     * @memberof Site
     */
    last_updated?: string;
    /**
     * 
     * @type {number}
     * @memberof Site
     */
    circuit_count?: number;
    /**
     * 
     * @type {number}
     * @memberof Site
     */
    device_count?: number;
    /**
     * 
     * @type {number}
     * @memberof Site
     */
    prefix_count?: number;
    /**
     * 
     * @type {number}
     * @memberof Site
     */
    rack_count?: number;
    /**
     * 
     * @type {number}
     * @memberof Site
     */
    virtualmachine_count?: number;
    /**
     * 
     * @type {number}
     * @memberof Site
     */
    vlan_count?: number;
}


