/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Status8
 */
export interface Status8 {
    /**
     * 
     * @type {string}
     * @memberof Status8
     */
    label: Status8LabelEnum;
    /**
     * 
     * @type {string}
     * @memberof Status8
     */
    value: Status8ValueEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum Status8LabelEnum {
    Container = 'Container',
    Active = 'Active',
    Reserved = 'Reserved',
    Deprecated = 'Deprecated'
}
/**
    * @export
    * @enum {string}
    */
export enum Status8ValueEnum {
    Container = 'container',
    Active = 'active',
    Reserved = 'reserved',
    Deprecated = 'deprecated'
}



