/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Status4
 */
export interface Status4 {
    /**
     * 
     * @type {string}
     * @memberof Status4
     */
    label: Status4LabelEnum;
    /**
     * 
     * @type {string}
     * @memberof Status4
     */
    value: Status4ValueEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum Status4LabelEnum {
    Reserved = 'Reserved',
    Available = 'Available',
    Planned = 'Planned',
    Active = 'Active',
    Deprecated = 'Deprecated'
}
/**
    * @export
    * @enum {string}
    */
export enum Status4ValueEnum {
    Reserved = 'reserved',
    Available = 'available',
    Planned = 'planned',
    Active = 'active',
    Deprecated = 'deprecated'
}



