/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Status5
 */
export interface Status5 {
    /**
     * 
     * @type {string}
     * @memberof Status5
     */
    label: Status5LabelEnum;
    /**
     * 
     * @type {string}
     * @memberof Status5
     */
    value: Status5ValueEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum Status5LabelEnum {
    Planned = 'Planned',
    Staging = 'Staging',
    Active = 'Active',
    Decommissioning = 'Decommissioning',
    Retired = 'Retired'
}
/**
    * @export
    * @enum {string}
    */
export enum Status5ValueEnum {
    Planned = 'planned',
    Staging = 'staging',
    Active = 'active',
    Decommissioning = 'decommissioning',
    Retired = 'retired'
}



