/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Status7
 */
export interface Status7 {
    /**
     * 
     * @type {string}
     * @memberof Status7
     */
    label: Status7LabelEnum;
    /**
     * 
     * @type {string}
     * @memberof Status7
     */
    value: Status7ValueEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum Status7LabelEnum {
    Active = 'Active',
    Reserved = 'Reserved',
    Deprecated = 'Deprecated',
    Dhcp = 'DHCP',
    Slaac = 'SLAAC'
}
/**
    * @export
    * @enum {string}
    */
export enum Status7ValueEnum {
    Active = 'active',
    Reserved = 'reserved',
    Deprecated = 'deprecated',
    Dhcp = 'dhcp',
    Slaac = 'slaac'
}



