/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Status10
 */
export interface Status10 {
    /**
     * 
     * @type {string}
     * @memberof Status10
     */
    label: Status10LabelEnum;
    /**
     * 
     * @type {string}
     * @memberof Status10
     */
    value: Status10ValueEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum Status10LabelEnum {
    Offline = 'Offline',
    Active = 'Active',
    Planned = 'Planned',
    Staged = 'Staged',
    Failed = 'Failed',
    Decommissioning = 'Decommissioning'
}
/**
    * @export
    * @enum {string}
    */
export enum Status10ValueEnum {
    Offline = 'offline',
    Active = 'active',
    Planned = 'planned',
    Staged = 'staged',
    Failed = 'failed',
    Decommissioning = 'decommissioning'
}



