/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Status6
 */
export interface Status6 {
    /**
     * 
     * @type {string}
     * @memberof Status6
     */
    label: Status6LabelEnum;
    /**
     * 
     * @type {string}
     * @memberof Status6
     */
    value: Status6ValueEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum Status6LabelEnum {
    Pending = 'Pending',
    Running = 'Running',
    Completed = 'Completed',
    Errored = 'Errored',
    Failed = 'Failed'
}
/**
    * @export
    * @enum {string}
    */
export enum Status6ValueEnum {
    Pending = 'pending',
    Running = 'running',
    Completed = 'completed',
    Errored = 'errored',
    Failed = 'failed'
}



