/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Status2
 */
export interface Status2 {
    /**
     * 
     * @type {string}
     * @memberof Status2
     */
    label: Status2LabelEnum;
    /**
     * 
     * @type {string}
     * @memberof Status2
     */
    value: Status2ValueEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum Status2LabelEnum {
    Offline = 'Offline',
    Active = 'Active',
    Planned = 'Planned',
    Staged = 'Staged',
    Failed = 'Failed',
    Inventory = 'Inventory',
    Decommissioning = 'Decommissioning'
}
/**
    * @export
    * @enum {string}
    */
export enum Status2ValueEnum {
    Offline = 'offline',
    Active = 'active',
    Planned = 'planned',
    Staged = 'staged',
    Failed = 'failed',
    Inventory = 'inventory',
    Decommissioning = 'decommissioning'
}



