/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Status1
 */
export interface Status1 {
    /**
     * 
     * @type {string}
     * @memberof Status1
     */
    label: Status1LabelEnum;
    /**
     * 
     * @type {string}
     * @memberof Status1
     */
    value: Status1ValueEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum Status1LabelEnum {
    Connected = 'Connected',
    Planned = 'Planned',
    Decommissioning = 'Decommissioning'
}
/**
    * @export
    * @enum {string}
    */
export enum Status1ValueEnum {
    Connected = 'connected',
    Planned = 'planned',
    Decommissioning = 'decommissioning'
}



