/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Status3
 */
export interface Status3 {
    /**
     * 
     * @type {string}
     * @memberof Status3
     */
    label: Status3LabelEnum;
    /**
     * 
     * @type {string}
     * @memberof Status3
     */
    value: Status3ValueEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum Status3LabelEnum {
    Offline = 'Offline',
    Active = 'Active',
    Planned = 'Planned',
    Failed = 'Failed'
}
/**
    * @export
    * @enum {string}
    */
export enum Status3ValueEnum {
    Offline = 'offline',
    Active = 'active',
    Planned = 'planned',
    Failed = 'failed'
}



