/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Type
 */
export interface Type {
    /**
     * 
     * @type {string}
     * @memberof Type
     */
    label: TypeLabelEnum;
    /**
     * 
     * @type {string}
     * @memberof Type
     */
    value: TypeValueEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum TypeLabelEnum {
    De9 = 'DE-9',
    Db25 = 'DB-25',
    Rj11 = 'RJ-11',
    Rj12 = 'RJ-12',
    Rj45 = 'RJ-45',
    UsbTypeA = 'USB Type A',
    UsbTypeB = 'USB Type B',
    UsbTypeC = 'USB Type C',
    UsbMiniA = 'USB Mini A',
    UsbMiniB = 'USB Mini B',
    UsbMicroA = 'USB Micro A',
    UsbMicroB = 'USB Micro B',
    Other = 'Other'
}
/**
    * @export
    * @enum {string}
    */
export enum TypeValueEnum {
    De9 = 'de-9',
    Db25 = 'db-25',
    Rj11 = 'rj-11',
    Rj12 = 'rj-12',
    Rj45 = 'rj-45',
    UsbA = 'usb-a',
    UsbB = 'usb-b',
    UsbC = 'usb-c',
    UsbMiniA = 'usb-mini-a',
    UsbMiniB = 'usb-mini-b',
    UsbMicroA = 'usb-micro-a',
    UsbMicroB = 'usb-micro-b',
    Other = 'other'
}



