/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Type7
 */
export interface Type7 {
    /**
     * 
     * @type {string}
     * @memberof Type7
     */
    label: Type7LabelEnum;
    /**
     * 
     * @type {string}
     * @memberof Type7
     */
    value: Type7ValueEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum Type7LabelEnum {
    Text = 'Text',
    Integer = 'Integer',
    BooleanTrueFalse = 'Boolean (true/false)',
    Date = 'Date',
    Url = 'URL',
    Selection = 'Selection'
}
/**
    * @export
    * @enum {string}
    */
export enum Type7ValueEnum {
    Text = 'text',
    Integer = 'integer',
    Boolean = 'boolean',
    Date = 'date',
    Url = 'url',
    Select = 'select'
}



