/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Type4
 */
export interface Type4 {
    /**
     * 
     * @type {string}
     * @memberof Type4
     */
    label: Type4LabelEnum;
    /**
     * 
     * @type {string}
     * @memberof Type4
     */
    value: Type4ValueEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum Type4LabelEnum {
    Primary = 'Primary',
    Redundant = 'Redundant'
}
/**
    * @export
    * @enum {string}
    */
export enum Type4ValueEnum {
    Primary = 'primary',
    Redundant = 'redundant'
}



