/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Type2
 */
export interface Type2 {
    /**
     * 
     * @type {string}
     * @memberof Type2
     */
    label: Type2LabelEnum;
    /**
     * 
     * @type {string}
     * @memberof Type2
     */
    value: Type2ValueEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum Type2LabelEnum {
    Virtual = 'Virtual',
    LinkAggregationGroupLag = 'Link Aggregation Group (LAG)',
    _100BaseTx10100Me = '100BASE-TX (10/100ME)',
    _1000BaseT1Ge = '1000BASE-T (1GE)',
    _25GbaseT25Ge = '2.5GBASE-T (2.5GE)',
    _5GbaseT5Ge = '5GBASE-T (5GE)',
    _10GbaseT10Ge = '10GBASE-T (10GE)',
    _10GbaseCx410Ge = '10GBASE-CX4 (10GE)',
    Gbic1Ge = 'GBIC (1GE)',
    Sfp1Ge = 'SFP (1GE)',
    Sfp10Ge = 'SFP+ (10GE)',
    Xfp10Ge = 'XFP (10GE)',
    Xenpak10Ge = 'XENPAK (10GE)',
    X210Ge = 'X2 (10GE)',
    Sfp2825Ge = 'SFP28 (25GE)',
    Qsfp40Ge = 'QSFP+ (40GE)',
    Qsfp2850Ge = 'QSFP28 (50GE)',
    Cfp100Ge = 'CFP (100GE)',
    Cfp2100Ge = 'CFP2 (100GE)',
    Cfp2200Ge = 'CFP2 (200GE)',
    Cfp4100Ge = 'CFP4 (100GE)',
    CiscoCpak100Ge = 'Cisco CPAK (100GE)',
    Qsfp28100Ge = 'QSFP28 (100GE)',
    Qsfp56200Ge = 'QSFP56 (200GE)',
    QsfpDd400Ge = 'QSFP-DD (400GE)',
    Osfp400Ge = 'OSFP (400GE)',
    Ieee80211a = 'IEEE 802.11a',
    Ieee80211bG = 'IEEE 802.11b/g',
    Ieee80211n = 'IEEE 802.11n',
    Ieee80211ac = 'IEEE 802.11ac',
    Ieee80211ad = 'IEEE 802.11ad',
    Ieee80211ax = 'IEEE 802.11ax',
    Gsm = 'GSM',
    Cdma = 'CDMA',
    Lte = 'LTE',
    Oc3Stm1 = 'OC-3/STM-1',
    Oc12Stm4 = 'OC-12/STM-4',
    Oc48Stm16 = 'OC-48/STM-16',
    Oc192Stm64 = 'OC-192/STM-64',
    Oc768Stm256 = 'OC-768/STM-256',
    Oc1920Stm640 = 'OC-1920/STM-640',
    Oc3840Stm1234 = 'OC-3840/STM-1234',
    Sfp1Gfc = 'SFP (1GFC)',
    Sfp2Gfc = 'SFP (2GFC)',
    Sfp4Gfc = 'SFP (4GFC)',
    Sfp8Gfc = 'SFP+ (8GFC)',
    Sfp16Gfc = 'SFP+ (16GFC)',
    Sfp2832Gfc = 'SFP28 (32GFC)',
    Qsfp28128Gfc = 'QSFP28 (128GFC)',
    Sdr2Gbps = 'SDR (2 Gbps)',
    Ddr4Gbps = 'DDR (4 Gbps)',
    Qdr8Gbps = 'QDR (8 Gbps)',
    Fdr1010Gbps = 'FDR10 (10 Gbps)',
    Fdr135Gbps = 'FDR (13.5 Gbps)',
    Edr25Gbps = 'EDR (25 Gbps)',
    Hdr50Gbps = 'HDR (50 Gbps)',
    Ndr100Gbps = 'NDR (100 Gbps)',
    Xdr250Gbps = 'XDR (250 Gbps)',
    T11544Mbps = 'T1 (1.544 Mbps)',
    E12048Mbps = 'E1 (2.048 Mbps)',
    T345Mbps = 'T3 (45 Mbps)',
    E334Mbps = 'E3 (34 Mbps)',
    CiscoStackWise = 'Cisco StackWise',
    CiscoStackWisePlus = 'Cisco StackWise Plus',
    CiscoFlexStack = 'Cisco FlexStack',
    CiscoFlexStackPlus = 'Cisco FlexStack Plus',
    JuniperVcp = 'Juniper VCP',
    ExtremeSummitStack = 'Extreme SummitStack',
    ExtremeSummitStack128 = 'Extreme SummitStack-128',
    ExtremeSummitStack256 = 'Extreme SummitStack-256',
    ExtremeSummitStack512 = 'Extreme SummitStack-512',
    Other = 'Other'
}
/**
    * @export
    * @enum {string}
    */
export enum Type2ValueEnum {
    Virtual = 'virtual',
    Lag = 'lag',
    _100baseTx = '100base-tx',
    _1000baseT = '1000base-t',
    _25gbaseT = '2.5gbase-t',
    _5gbaseT = '5gbase-t',
    _10gbaseT = '10gbase-t',
    _10gbaseCx4 = '10gbase-cx4',
    _1000baseXGbic = '1000base-x-gbic',
    _1000baseXSfp = '1000base-x-sfp',
    _10gbaseXSfpp = '10gbase-x-sfpp',
    _10gbaseXXfp = '10gbase-x-xfp',
    _10gbaseXXenpak = '10gbase-x-xenpak',
    _10gbaseXX2 = '10gbase-x-x2',
    _25gbaseXSfp28 = '25gbase-x-sfp28',
    _40gbaseXQsfpp = '40gbase-x-qsfpp',
    _50gbaseXSfp28 = '50gbase-x-sfp28',
    _100gbaseXCfp = '100gbase-x-cfp',
    _100gbaseXCfp2 = '100gbase-x-cfp2',
    _200gbaseXCfp2 = '200gbase-x-cfp2',
    _100gbaseXCfp4 = '100gbase-x-cfp4',
    _100gbaseXCpak = '100gbase-x-cpak',
    _100gbaseXQsfp28 = '100gbase-x-qsfp28',
    _200gbaseXQsfp56 = '200gbase-x-qsfp56',
    _400gbaseXQsfpdd = '400gbase-x-qsfpdd',
    _400gbaseXOsfp = '400gbase-x-osfp',
    Ieee80211a = 'ieee802.11a',
    Ieee80211g = 'ieee802.11g',
    Ieee80211n = 'ieee802.11n',
    Ieee80211ac = 'ieee802.11ac',
    Ieee80211ad = 'ieee802.11ad',
    Ieee80211ax = 'ieee802.11ax',
    Gsm = 'gsm',
    Cdma = 'cdma',
    Lte = 'lte',
    SonetOc3 = 'sonet-oc3',
    SonetOc12 = 'sonet-oc12',
    SonetOc48 = 'sonet-oc48',
    SonetOc192 = 'sonet-oc192',
    SonetOc768 = 'sonet-oc768',
    SonetOc1920 = 'sonet-oc1920',
    SonetOc3840 = 'sonet-oc3840',
    _1gfcSfp = '1gfc-sfp',
    _2gfcSfp = '2gfc-sfp',
    _4gfcSfp = '4gfc-sfp',
    _8gfcSfpp = '8gfc-sfpp',
    _16gfcSfpp = '16gfc-sfpp',
    _32gfcSfp28 = '32gfc-sfp28',
    _128gfcSfp28 = '128gfc-sfp28',
    InfinibandSdr = 'infiniband-sdr',
    InfinibandDdr = 'infiniband-ddr',
    InfinibandQdr = 'infiniband-qdr',
    InfinibandFdr10 = 'infiniband-fdr10',
    InfinibandFdr = 'infiniband-fdr',
    InfinibandEdr = 'infiniband-edr',
    InfinibandHdr = 'infiniband-hdr',
    InfinibandNdr = 'infiniband-ndr',
    InfinibandXdr = 'infiniband-xdr',
    T1 = 't1',
    E1 = 'e1',
    T3 = 't3',
    E3 = 'e3',
    CiscoStackwise = 'cisco-stackwise',
    CiscoStackwisePlus = 'cisco-stackwise-plus',
    CiscoFlexstack = 'cisco-flexstack',
    CiscoFlexstackPlus = 'cisco-flexstack-plus',
    JuniperVcp = 'juniper-vcp',
    ExtremeSummitstack = 'extreme-summitstack',
    ExtremeSummitstack128 = 'extreme-summitstack-128',
    ExtremeSummitstack256 = 'extreme-summitstack-256',
    ExtremeSummitstack512 = 'extreme-summitstack-512',
    Other = 'other'
}



