/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Type1
 */
export interface Type1 {
    /**
     * 
     * @type {string}
     * @memberof Type1
     */
    label: Type1LabelEnum;
    /**
     * 
     * @type {string}
     * @memberof Type1
     */
    value: Type1ValueEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum Type1LabelEnum {
    _8P8C = '8P8C',
    _8P6C = '8P6C',
    _8P4C = '8P4C',
    _8P2C = '8P2C',
    _110Punch = '110 Punch',
    Bnc = 'BNC',
    Mrj21 = 'MRJ21',
    Fc = 'FC',
    Lc = 'LC',
    LcApc = 'LC/APC',
    Lsh = 'LSH',
    LshApc = 'LSH/APC',
    Mpo = 'MPO',
    Mtrj = 'MTRJ',
    Sc = 'SC',
    ScApc = 'SC/APC',
    St = 'ST',
    Cs = 'CS',
    Sn = 'SN',
    Splice = 'Splice'
}
/**
    * @export
    * @enum {string}
    */
export enum Type1ValueEnum {
    _8p8c = '8p8c',
    _8p6c = '8p6c',
    _8p4c = '8p4c',
    _8p2c = '8p2c',
    _110Punch = '110-punch',
    Bnc = 'bnc',
    Mrj21 = 'mrj21',
    Fc = 'fc',
    Lc = 'lc',
    LcApc = 'lc-apc',
    Lsh = 'lsh',
    LshApc = 'lsh-apc',
    Mpo = 'mpo',
    Mtrj = 'mtrj',
    Sc = 'sc',
    ScApc = 'sc-apc',
    St = 'st',
    Cs = 'cs',
    Sn = 'sn',
    Splice = 'splice'
}



