/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedCluster } from './nested-cluster';
import { NestedDeviceRole } from './nested-device-role';
import { NestedIPAddress } from './nested-ipaddress';
import { NestedPlatform } from './nested-platform';
import { NestedSite } from './nested-site';
import { NestedTag } from './nested-tag';
import { NestedTenant } from './nested-tenant';
import { Status10 } from './status10';

/**
 * 
 * @export
 * @interface VirtualMachineWithConfigContext
 */
export interface VirtualMachineWithConfigContext {
    /**
     * 
     * @type {number}
     * @memberof VirtualMachineWithConfigContext
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof VirtualMachineWithConfigContext
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof VirtualMachineWithConfigContext
     */
    name: string;
    /**
     * 
     * @type {Status10}
     * @memberof VirtualMachineWithConfigContext
     */
    status?: Status10;
    /**
     * 
     * @type {NestedSite}
     * @memberof VirtualMachineWithConfigContext
     */
    site?: NestedSite;
    /**
     * 
     * @type {NestedCluster}
     * @memberof VirtualMachineWithConfigContext
     */
    cluster: NestedCluster | null;
    /**
     * 
     * @type {NestedDeviceRole}
     * @memberof VirtualMachineWithConfigContext
     */
    role?: NestedDeviceRole;
    /**
     * 
     * @type {NestedTenant}
     * @memberof VirtualMachineWithConfigContext
     */
    tenant?: NestedTenant | null;
    /**
     * 
     * @type {NestedPlatform}
     * @memberof VirtualMachineWithConfigContext
     */
    platform?: NestedPlatform | null;
    /**
     * 
     * @type {NestedIPAddress}
     * @memberof VirtualMachineWithConfigContext
     */
    primary_ip?: NestedIPAddress;
    /**
     * 
     * @type {NestedIPAddress}
     * @memberof VirtualMachineWithConfigContext
     */
    primary_ip4?: NestedIPAddress;
    /**
     * 
     * @type {NestedIPAddress}
     * @memberof VirtualMachineWithConfigContext
     */
    primary_ip6?: NestedIPAddress;
    /**
     * 
     * @type {number}
     * @memberof VirtualMachineWithConfigContext
     */
    vcpus?: number | null;
    /**
     * 
     * @type {number}
     * @memberof VirtualMachineWithConfigContext
     */
    memory?: number | null;
    /**
     * 
     * @type {number}
     * @memberof VirtualMachineWithConfigContext
     */
    disk?: number | null;
    /**
     * 
     * @type {string}
     * @memberof VirtualMachineWithConfigContext
     */
    comments?: string;
    /**
     * 
     * @type {string}
     * @memberof VirtualMachineWithConfigContext
     */
    local_context_data?: string | null;
    /**
     * 
     * @type {Array<NestedTag>}
     * @memberof VirtualMachineWithConfigContext
     */
    tags?: Array<NestedTag>;
    /**
     * 
     * @type {object}
     * @memberof VirtualMachineWithConfigContext
     */
    custom_fields?: object;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof VirtualMachineWithConfigContext
     */
    config_context?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof VirtualMachineWithConfigContext
     */
    created?: string;
    /**
     * 
     * @type {string}
     * @memberof VirtualMachineWithConfigContext
     */
    last_updated?: string;
}


