/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedRole } from './nested-role';
import { NestedSite } from './nested-site';
import { NestedTag } from './nested-tag';
import { NestedTenant } from './nested-tenant';
import { NestedVLANGroup } from './nested-vlangroup';
import { Status9 } from './status9';

/**
 * 
 * @export
 * @interface VLAN
 */
export interface VLAN {
    /**
     * 
     * @type {number}
     * @memberof VLAN
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof VLAN
     */
    url?: string;
    /**
     * 
     * @type {NestedSite}
     * @memberof VLAN
     */
    site?: NestedSite;
    /**
     * 
     * @type {NestedVLANGroup}
     * @memberof VLAN
     */
    group?: NestedVLANGroup | null;
    /**
     * 
     * @type {number}
     * @memberof VLAN
     */
    vid: number;
    /**
     * 
     * @type {string}
     * @memberof VLAN
     */
    name: string;
    /**
     * 
     * @type {NestedTenant}
     * @memberof VLAN
     */
    tenant?: NestedTenant | null;
    /**
     * 
     * @type {Status9}
     * @memberof VLAN
     */
    status?: Status9;
    /**
     * 
     * @type {NestedRole}
     * @memberof VLAN
     */
    role?: NestedRole | null;
    /**
     * 
     * @type {string}
     * @memberof VLAN
     */
    description?: string;
    /**
     * 
     * @type {Array<NestedTag>}
     * @memberof VLAN
     */
    tags?: Array<NestedTag>;
    /**
     * 
     * @type {string}
     * @memberof VLAN
     */
    display_name?: string;
    /**
     * 
     * @type {object}
     * @memberof VLAN
     */
    custom_fields?: object;
    /**
     * 
     * @type {string}
     * @memberof VLAN
     */
    created?: string;
    /**
     * 
     * @type {string}
     * @memberof VLAN
     */
    last_updated?: string;
    /**
     * 
     * @type {number}
     * @memberof VLAN
     */
    prefix_count?: number;
}


