/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Mode } from './mode';
import { NestedTag } from './nested-tag';
import { NestedVLAN } from './nested-vlan';
import { NestedVirtualMachine } from './nested-virtual-machine';

/**
 * 
 * @export
 * @interface VMInterface
 */
export interface VMInterface {
    /**
     * 
     * @type {number}
     * @memberof VMInterface
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof VMInterface
     */
    url?: string;
    /**
     * 
     * @type {NestedVirtualMachine}
     * @memberof VMInterface
     */
    virtual_machine: NestedVirtualMachine | null;
    /**
     * 
     * @type {string}
     * @memberof VMInterface
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof VMInterface
     */
    enabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof VMInterface
     */
    mtu?: number | null;
    /**
     * 
     * @type {string}
     * @memberof VMInterface
     */
    mac_address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VMInterface
     */
    description?: string;
    /**
     * 
     * @type {Mode}
     * @memberof VMInterface
     */
    mode?: Mode;
    /**
     * 
     * @type {NestedVLAN}
     * @memberof VMInterface
     */
    untagged_vlan?: NestedVLAN | null;
    /**
     * 
     * @type {Set<NestedVLAN>}
     * @memberof VMInterface
     */
    tagged_vlans?: Set<NestedVLAN>;
    /**
     * 
     * @type {Array<NestedTag>}
     * @memberof VMInterface
     */
    tags?: Array<NestedTag>;
}


