/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WritableAvailableIP
 */
export interface WritableAvailableIP {
    /**
     * 
     * @type {number}
     * @memberof WritableAvailableIP
     */
    family?: number;
    /**
     * 
     * @type {string}
     * @memberof WritableAvailableIP
     */
    address?: string;
}


