/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WritableConfigContext
 */
export interface WritableConfigContext {
    /**
     * 
     * @type {number}
     * @memberof WritableConfigContext
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof WritableConfigContext
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof WritableConfigContext
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof WritableConfigContext
     */
    weight?: number;
    /**
     * 
     * @type {string}
     * @memberof WritableConfigContext
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof WritableConfigContext
     */
    is_active?: boolean;
    /**
     * 
     * @type {Set<number>}
     * @memberof WritableConfigContext
     */
    regions?: Set<number>;
    /**
     * 
     * @type {Set<number>}
     * @memberof WritableConfigContext
     */
    sites?: Set<number>;
    /**
     * 
     * @type {Set<number>}
     * @memberof WritableConfigContext
     */
    roles?: Set<number>;
    /**
     * 
     * @type {Set<number>}
     * @memberof WritableConfigContext
     */
    platforms?: Set<number>;
    /**
     * 
     * @type {Set<number>}
     * @memberof WritableConfigContext
     */
    cluster_groups?: Set<number>;
    /**
     * 
     * @type {Set<number>}
     * @memberof WritableConfigContext
     */
    clusters?: Set<number>;
    /**
     * 
     * @type {Set<number>}
     * @memberof WritableConfigContext
     */
    tenant_groups?: Set<number>;
    /**
     * 
     * @type {Set<number>}
     * @memberof WritableConfigContext
     */
    tenants?: Set<number>;
    /**
     * 
     * @type {Set<string>}
     * @memberof WritableConfigContext
     */
    tags?: Set<string>;
    /**
     * 
     * @type {string}
     * @memberof WritableConfigContext
     */
    data: string;
    /**
     * 
     * @type {string}
     * @memberof WritableConfigContext
     */
    created?: string;
    /**
     * 
     * @type {string}
     * @memberof WritableConfigContext
     */
    last_updated?: string;
}


