/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedCable } from './nested-cable';
import { NestedTag } from './nested-tag';

/**
 * 
 * @export
 * @interface WritableFrontPort
 */
export interface WritableFrontPort {
    /**
     * 
     * @type {number}
     * @memberof WritableFrontPort
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof WritableFrontPort
     */
    url?: string;
    /**
     * 
     * @type {number}
     * @memberof WritableFrontPort
     */
    device: number;
    /**
     * 
     * @type {string}
     * @memberof WritableFrontPort
     */
    name: string;
    /**
     * Physical label
     * @type {string}
     * @memberof WritableFrontPort
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof WritableFrontPort
     */
    type: WritableFrontPortTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof WritableFrontPort
     */
    rear_port: number;
    /**
     * 
     * @type {number}
     * @memberof WritableFrontPort
     */
    rear_port_position?: number;
    /**
     * 
     * @type {string}
     * @memberof WritableFrontPort
     */
    description?: string;
    /**
     * 
     * @type {NestedCable}
     * @memberof WritableFrontPort
     */
    cable?: NestedCable;
    /**
     *  Return the appropriate serializer for the cable termination model. 
     * @type {{ [key: string]: string; }}
     * @memberof WritableFrontPort
     */
    cable_peer?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof WritableFrontPort
     */
    cable_peer_type?: string;
    /**
     * 
     * @type {Array<NestedTag>}
     * @memberof WritableFrontPort
     */
    tags?: Array<NestedTag>;
}

/**
    * @export
    * @enum {string}
    */
export enum WritableFrontPortTypeEnum {
    _8p8c = '8p8c',
    _8p6c = '8p6c',
    _8p4c = '8p4c',
    _8p2c = '8p2c',
    _110Punch = '110-punch',
    Bnc = 'bnc',
    Mrj21 = 'mrj21',
    Fc = 'fc',
    Lc = 'lc',
    LcApc = 'lc-apc',
    Lsh = 'lsh',
    LshApc = 'lsh-apc',
    Mpo = 'mpo',
    Mtrj = 'mtrj',
    Sc = 'sc',
    ScApc = 'sc-apc',
    St = 'st',
    Cs = 'cs',
    Sn = 'sn',
    Splice = 'splice'
}



