/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WritableUser
 */
export interface WritableUser {
    /**
     * 
     * @type {number}
     * @memberof WritableUser
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof WritableUser
     */
    url?: string;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof WritableUser
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof WritableUser
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof WritableUser
     */
    first_name?: string;
    /**
     * 
     * @type {string}
     * @memberof WritableUser
     */
    last_name?: string;
    /**
     * 
     * @type {string}
     * @memberof WritableUser
     */
    email?: string;
    /**
     * Designates whether the user can log into this admin site.
     * @type {boolean}
     * @memberof WritableUser
     */
    is_staff?: boolean;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     * @type {boolean}
     * @memberof WritableUser
     */
    is_active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof WritableUser
     */
    date_joined?: string;
    /**
     * The groups this user belongs to. A user will get all permissions granted to each of their groups.
     * @type {Set<number>}
     * @memberof WritableUser
     */
    groups?: Set<number>;
}


