/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedRouteTarget } from './nested-route-target';
import { NestedTag } from './nested-tag';

/**
 * 
 * @export
 * @interface WritableVRF
 */
export interface WritableVRF {
    /**
     * 
     * @type {number}
     * @memberof WritableVRF
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof WritableVRF
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof WritableVRF
     */
    name: string;
    /**
     * Unique route distinguisher (as defined in RFC 4364)
     * @type {string}
     * @memberof WritableVRF
     */
    rd?: string | null;
    /**
     * 
     * @type {number}
     * @memberof WritableVRF
     */
    tenant?: number | null;
    /**
     * Prevent duplicate prefixes/IP addresses within this VRF
     * @type {boolean}
     * @memberof WritableVRF
     */
    enforce_unique?: boolean;
    /**
     * 
     * @type {string}
     * @memberof WritableVRF
     */
    description?: string;
    /**
     * 
     * @type {Array<NestedRouteTarget>}
     * @memberof WritableVRF
     */
    import_targets?: Array<NestedRouteTarget> | null;
    /**
     * 
     * @type {Array<NestedRouteTarget>}
     * @memberof WritableVRF
     */
    export_targets?: Array<NestedRouteTarget> | null;
    /**
     * 
     * @type {Array<NestedTag>}
     * @memberof WritableVRF
     */
    tags?: Array<NestedTag>;
    /**
     * 
     * @type {string}
     * @memberof WritableVRF
     */
    display_name?: string;
    /**
     * 
     * @type {object}
     * @memberof WritableVRF
     */
    custom_fields?: object;
    /**
     * 
     * @type {string}
     * @memberof WritableVRF
     */
    created?: string;
    /**
     * 
     * @type {string}
     * @memberof WritableVRF
     */
    last_updated?: string;
    /**
     * 
     * @type {number}
     * @memberof WritableVRF
     */
    ipaddress_count?: number;
    /**
     * 
     * @type {number}
     * @memberof WritableVRF
     */
    prefix_count?: number;
}


