/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedTag } from './nested-tag';

/**
 * 
 * @export
 * @interface WritableSite
 */
export interface WritableSite {
    /**
     * 
     * @type {number}
     * @memberof WritableSite
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof WritableSite
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof WritableSite
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof WritableSite
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof WritableSite
     */
    status?: WritableSiteStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof WritableSite
     */
    region?: number | null;
    /**
     * 
     * @type {number}
     * @memberof WritableSite
     */
    tenant?: number | null;
    /**
     * Local facility ID or description
     * @type {string}
     * @memberof WritableSite
     */
    facility?: string;
    /**
     * 32-bit autonomous system number
     * @type {number}
     * @memberof WritableSite
     */
    asn?: number | null;
    /**
     * 
     * @type {string}
     * @memberof WritableSite
     */
    time_zone?: string;
    /**
     * 
     * @type {string}
     * @memberof WritableSite
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof WritableSite
     */
    physical_address?: string;
    /**
     * 
     * @type {string}
     * @memberof WritableSite
     */
    shipping_address?: string;
    /**
     * GPS coordinate (latitude)
     * @type {string}
     * @memberof WritableSite
     */
    latitude?: string | null;
    /**
     * GPS coordinate (longitude)
     * @type {string}
     * @memberof WritableSite
     */
    longitude?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WritableSite
     */
    contact_name?: string;
    /**
     * 
     * @type {string}
     * @memberof WritableSite
     */
    contact_phone?: string;
    /**
     * 
     * @type {string}
     * @memberof WritableSite
     */
    contact_email?: string;
    /**
     * 
     * @type {string}
     * @memberof WritableSite
     */
    comments?: string;
    /**
     * 
     * @type {Array<NestedTag>}
     * @memberof WritableSite
     */
    tags?: Array<NestedTag>;
    /**
     * 
     * @type {object}
     * @memberof WritableSite
     */
    custom_fields?: object;
    /**
     * 
     * @type {string}
     * @memberof WritableSite
     */
    created?: string;
    /**
     * 
     * @type {string}
     * @memberof WritableSite
     */
    last_updated?: string;
    /**
     * 
     * @type {number}
     * @memberof WritableSite
     */
    circuit_count?: number;
    /**
     * 
     * @type {number}
     * @memberof WritableSite
     */
    device_count?: number;
    /**
     * 
     * @type {number}
     * @memberof WritableSite
     */
    prefix_count?: number;
    /**
     * 
     * @type {number}
     * @memberof WritableSite
     */
    rack_count?: number;
    /**
     * 
     * @type {number}
     * @memberof WritableSite
     */
    virtualmachine_count?: number;
    /**
     * 
     * @type {number}
     * @memberof WritableSite
     */
    vlan_count?: number;
}

/**
    * @export
    * @enum {string}
    */
export enum WritableSiteStatusEnum {
    Planned = 'planned',
    Staging = 'staging',
    Active = 'active',
    Decommissioning = 'decommissioning',
    Retired = 'retired'
}



