/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedDevice } from './nested-device';
import { NestedTag } from './nested-tag';

/**
 * 
 * @export
 * @interface WritableDeviceWithConfigContext
 */
export interface WritableDeviceWithConfigContext {
    /**
     * 
     * @type {number}
     * @memberof WritableDeviceWithConfigContext
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof WritableDeviceWithConfigContext
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof WritableDeviceWithConfigContext
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WritableDeviceWithConfigContext
     */
    display_name?: string;
    /**
     * 
     * @type {number}
     * @memberof WritableDeviceWithConfigContext
     */
    device_type: number;
    /**
     * 
     * @type {number}
     * @memberof WritableDeviceWithConfigContext
     */
    device_role: number;
    /**
     * 
     * @type {number}
     * @memberof WritableDeviceWithConfigContext
     */
    tenant?: number | null;
    /**
     * 
     * @type {number}
     * @memberof WritableDeviceWithConfigContext
     */
    platform?: number | null;
    /**
     * 
     * @type {string}
     * @memberof WritableDeviceWithConfigContext
     */
    serial?: string;
    /**
     * A unique tag used to identify this device
     * @type {string}
     * @memberof WritableDeviceWithConfigContext
     */
    asset_tag?: string | null;
    /**
     * 
     * @type {number}
     * @memberof WritableDeviceWithConfigContext
     */
    site: number;
    /**
     * 
     * @type {number}
     * @memberof WritableDeviceWithConfigContext
     */
    rack?: number | null;
    /**
     * The lowest-numbered unit occupied by the device
     * @type {number}
     * @memberof WritableDeviceWithConfigContext
     */
    position?: number | null;
    /**
     * 
     * @type {string}
     * @memberof WritableDeviceWithConfigContext
     */
    face?: WritableDeviceWithConfigContextFaceEnum;
    /**
     * 
     * @type {NestedDevice}
     * @memberof WritableDeviceWithConfigContext
     */
    parent_device?: NestedDevice;
    /**
     * 
     * @type {string}
     * @memberof WritableDeviceWithConfigContext
     */
    status?: WritableDeviceWithConfigContextStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof WritableDeviceWithConfigContext
     */
    primary_ip?: string;
    /**
     * 
     * @type {number}
     * @memberof WritableDeviceWithConfigContext
     */
    primary_ip4?: number | null;
    /**
     * 
     * @type {number}
     * @memberof WritableDeviceWithConfigContext
     */
    primary_ip6?: number | null;
    /**
     * 
     * @type {number}
     * @memberof WritableDeviceWithConfigContext
     */
    cluster?: number | null;
    /**
     * 
     * @type {number}
     * @memberof WritableDeviceWithConfigContext
     */
    virtual_chassis?: number | null;
    /**
     * 
     * @type {number}
     * @memberof WritableDeviceWithConfigContext
     */
    vc_position?: number | null;
    /**
     * 
     * @type {number}
     * @memberof WritableDeviceWithConfigContext
     */
    vc_priority?: number | null;
    /**
     * 
     * @type {string}
     * @memberof WritableDeviceWithConfigContext
     */
    comments?: string;
    /**
     * 
     * @type {string}
     * @memberof WritableDeviceWithConfigContext
     */
    local_context_data?: string | null;
    /**
     * 
     * @type {Array<NestedTag>}
     * @memberof WritableDeviceWithConfigContext
     */
    tags?: Array<NestedTag>;
    /**
     * 
     * @type {object}
     * @memberof WritableDeviceWithConfigContext
     */
    custom_fields?: object;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof WritableDeviceWithConfigContext
     */
    config_context?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof WritableDeviceWithConfigContext
     */
    created?: string;
    /**
     * 
     * @type {string}
     * @memberof WritableDeviceWithConfigContext
     */
    last_updated?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum WritableDeviceWithConfigContextFaceEnum {
    Front = 'front',
    Rear = 'rear'
}
/**
    * @export
    * @enum {string}
    */
export enum WritableDeviceWithConfigContextStatusEnum {
    Offline = 'offline',
    Active = 'active',
    Planned = 'planned',
    Staged = 'staged',
    Failed = 'failed',
    Inventory = 'inventory',
    Decommissioning = 'decommissioning'
}



