/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WritablePlatform
 */
export interface WritablePlatform {
    /**
     * 
     * @type {number}
     * @memberof WritablePlatform
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof WritablePlatform
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof WritablePlatform
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof WritablePlatform
     */
    slug: string;
    /**
     * Optionally limit this platform to devices of a certain manufacturer
     * @type {number}
     * @memberof WritablePlatform
     */
    manufacturer?: number | null;
    /**
     * The name of the NAPALM driver to use when interacting with devices
     * @type {string}
     * @memberof WritablePlatform
     */
    napalm_driver?: string;
    /**
     * Additional arguments to pass when initiating the NAPALM driver (JSON format)
     * @type {string}
     * @memberof WritablePlatform
     */
    napalm_args?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WritablePlatform
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof WritablePlatform
     */
    device_count?: number;
    /**
     * 
     * @type {number}
     * @memberof WritablePlatform
     */
    virtualmachine_count?: number;
}


