/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedTag } from './nested-tag';

/**
 * 
 * @export
 * @interface WritableVMInterface
 */
export interface WritableVMInterface {
    /**
     * 
     * @type {number}
     * @memberof WritableVMInterface
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof WritableVMInterface
     */
    url?: string;
    /**
     * 
     * @type {number}
     * @memberof WritableVMInterface
     */
    virtual_machine: number;
    /**
     * 
     * @type {string}
     * @memberof WritableVMInterface
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof WritableVMInterface
     */
    enabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof WritableVMInterface
     */
    mtu?: number | null;
    /**
     * 
     * @type {string}
     * @memberof WritableVMInterface
     */
    mac_address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WritableVMInterface
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof WritableVMInterface
     */
    mode?: WritableVMInterfaceModeEnum;
    /**
     * 
     * @type {number}
     * @memberof WritableVMInterface
     */
    untagged_vlan?: number | null;
    /**
     * 
     * @type {Set<number>}
     * @memberof WritableVMInterface
     */
    tagged_vlans?: Set<number>;
    /**
     * 
     * @type {Array<NestedTag>}
     * @memberof WritableVMInterface
     */
    tags?: Array<NestedTag>;
}

/**
    * @export
    * @enum {string}
    */
export enum WritableVMInterfaceModeEnum {
    Access = 'access',
    Tagged = 'tagged',
    TaggedAll = 'tagged-all'
}



