/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WritableCustomField
 */
export interface WritableCustomField {
    /**
     * 
     * @type {number}
     * @memberof WritableCustomField
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof WritableCustomField
     */
    url?: string;
    /**
     * 
     * @type {Set<string>}
     * @memberof WritableCustomField
     */
    content_types: Set<string>;
    /**
     * 
     * @type {string}
     * @memberof WritableCustomField
     */
    type?: WritableCustomFieldTypeEnum;
    /**
     * Internal field name
     * @type {string}
     * @memberof WritableCustomField
     */
    name: string;
    /**
     * Name of the field as displayed to users (if not provided, the field\'s name will be used)
     * @type {string}
     * @memberof WritableCustomField
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof WritableCustomField
     */
    description?: string;
    /**
     * If true, this field is required when creating new objects or editing an existing object.
     * @type {boolean}
     * @memberof WritableCustomField
     */
    required?: boolean;
    /**
     * Loose matches any instance of a given string; exact matches the entire field.
     * @type {string}
     * @memberof WritableCustomField
     */
    filter_logic?: WritableCustomFieldFilterLogicEnum;
    /**
     * Default value for the field (must be a JSON value). Encapsulate strings with double quotes (e.g. \"Foo\").
     * @type {string}
     * @memberof WritableCustomField
     */
    _default?: string | null;
    /**
     * Fields with higher weights appear lower in a form.
     * @type {number}
     * @memberof WritableCustomField
     */
    weight?: number;
    /**
     * Minimum allowed value (for numeric fields)
     * @type {number}
     * @memberof WritableCustomField
     */
    validation_minimum?: number | null;
    /**
     * Maximum allowed value (for numeric fields)
     * @type {number}
     * @memberof WritableCustomField
     */
    validation_maximum?: number | null;
    /**
     * Regular expression to enforce on text field values. Use ^ and $ to force matching of entire string. For example, <code>^[A-Z]{3}$</code> will limit values to exactly three uppercase letters.
     * @type {string}
     * @memberof WritableCustomField
     */
    validation_regex?: string;
    /**
     * Comma-separated list of available choices (for selection fields)
     * @type {Array<string>}
     * @memberof WritableCustomField
     */
    choices?: Array<string> | null;
}

/**
    * @export
    * @enum {string}
    */
export enum WritableCustomFieldTypeEnum {
    Text = 'text',
    Integer = 'integer',
    Boolean = 'boolean',
    Date = 'date',
    Url = 'url',
    Select = 'select'
}
/**
    * @export
    * @enum {string}
    */
export enum WritableCustomFieldFilterLogicEnum {
    Disabled = 'disabled',
    Loose = 'loose',
    Exact = 'exact'
}



