/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedTag } from './nested-tag';

/**
 * 
 * @export
 * @interface WritableAggregate
 */
export interface WritableAggregate {
    /**
     * 
     * @type {number}
     * @memberof WritableAggregate
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof WritableAggregate
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof WritableAggregate
     */
    family?: string;
    /**
     * 
     * @type {string}
     * @memberof WritableAggregate
     */
    prefix: string;
    /**
     * 
     * @type {number}
     * @memberof WritableAggregate
     */
    rir: number;
    /**
     * 
     * @type {number}
     * @memberof WritableAggregate
     */
    tenant?: number | null;
    /**
     * 
     * @type {string}
     * @memberof WritableAggregate
     */
    date_added?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WritableAggregate
     */
    description?: string;
    /**
     * 
     * @type {Array<NestedTag>}
     * @memberof WritableAggregate
     */
    tags?: Array<NestedTag>;
    /**
     * 
     * @type {object}
     * @memberof WritableAggregate
     */
    custom_fields?: object;
    /**
     * 
     * @type {string}
     * @memberof WritableAggregate
     */
    created?: string;
    /**
     * 
     * @type {string}
     * @memberof WritableAggregate
     */
    last_updated?: string;
}


