/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedTag } from './nested-tag';

/**
 * 
 * @export
 * @interface WritableService
 */
export interface WritableService {
    /**
     * 
     * @type {number}
     * @memberof WritableService
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof WritableService
     */
    url?: string;
    /**
     * 
     * @type {number}
     * @memberof WritableService
     */
    device?: number | null;
    /**
     * 
     * @type {number}
     * @memberof WritableService
     */
    virtual_machine?: number | null;
    /**
     * 
     * @type {string}
     * @memberof WritableService
     */
    name: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof WritableService
     */
    ports: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof WritableService
     */
    protocol: WritableServiceProtocolEnum;
    /**
     * 
     * @type {Set<number>}
     * @memberof WritableService
     */
    ipaddresses?: Set<number>;
    /**
     * 
     * @type {string}
     * @memberof WritableService
     */
    description?: string;
    /**
     * 
     * @type {Array<NestedTag>}
     * @memberof WritableService
     */
    tags?: Array<NestedTag>;
    /**
     * 
     * @type {object}
     * @memberof WritableService
     */
    custom_fields?: object;
    /**
     * 
     * @type {string}
     * @memberof WritableService
     */
    created?: string;
    /**
     * 
     * @type {string}
     * @memberof WritableService
     */
    last_updated?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum WritableServiceProtocolEnum {
    Tcp = 'tcp',
    Udp = 'udp'
}



