/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedCable } from './nested-cable';
import { NestedTag } from './nested-tag';

/**
 * 
 * @export
 * @interface WritableConsoleServerPort
 */
export interface WritableConsoleServerPort {
    /**
     * 
     * @type {number}
     * @memberof WritableConsoleServerPort
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof WritableConsoleServerPort
     */
    url?: string;
    /**
     * 
     * @type {number}
     * @memberof WritableConsoleServerPort
     */
    device: number;
    /**
     * 
     * @type {string}
     * @memberof WritableConsoleServerPort
     */
    name: string;
    /**
     * Physical label
     * @type {string}
     * @memberof WritableConsoleServerPort
     */
    label?: string;
    /**
     * Physical port type
     * @type {string}
     * @memberof WritableConsoleServerPort
     */
    type?: WritableConsoleServerPortTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof WritableConsoleServerPort
     */
    description?: string;
    /**
     * 
     * @type {NestedCable}
     * @memberof WritableConsoleServerPort
     */
    cable?: NestedCable;
    /**
     *  Return the appropriate serializer for the cable termination model. 
     * @type {{ [key: string]: string; }}
     * @memberof WritableConsoleServerPort
     */
    cable_peer?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof WritableConsoleServerPort
     */
    cable_peer_type?: string;
    /**
     *  Return the appropriate serializer for the type of connected object. 
     * @type {{ [key: string]: string; }}
     * @memberof WritableConsoleServerPort
     */
    connected_endpoint?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof WritableConsoleServerPort
     */
    connected_endpoint_type?: string;
    /**
     * 
     * @type {boolean}
     * @memberof WritableConsoleServerPort
     */
    connected_endpoint_reachable?: boolean;
    /**
     * 
     * @type {Array<NestedTag>}
     * @memberof WritableConsoleServerPort
     */
    tags?: Array<NestedTag>;
}

/**
    * @export
    * @enum {string}
    */
export enum WritableConsoleServerPortTypeEnum {
    De9 = 'de-9',
    Db25 = 'db-25',
    Rj11 = 'rj-11',
    Rj12 = 'rj-12',
    Rj45 = 'rj-45',
    UsbA = 'usb-a',
    UsbB = 'usb-b',
    UsbC = 'usb-c',
    UsbMiniA = 'usb-mini-a',
    UsbMiniB = 'usb-mini-b',
    UsbMicroA = 'usb-micro-a',
    UsbMicroB = 'usb-micro-b',
    Other = 'other'
}



