/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedTag } from './nested-tag';

/**
 * 
 * @export
 * @interface WritableCluster
 */
export interface WritableCluster {
    /**
     * 
     * @type {number}
     * @memberof WritableCluster
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof WritableCluster
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof WritableCluster
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof WritableCluster
     */
    type: number;
    /**
     * 
     * @type {number}
     * @memberof WritableCluster
     */
    group?: number | null;
    /**
     * 
     * @type {number}
     * @memberof WritableCluster
     */
    tenant?: number | null;
    /**
     * 
     * @type {number}
     * @memberof WritableCluster
     */
    site?: number | null;
    /**
     * 
     * @type {string}
     * @memberof WritableCluster
     */
    comments?: string;
    /**
     * 
     * @type {Array<NestedTag>}
     * @memberof WritableCluster
     */
    tags?: Array<NestedTag>;
    /**
     * 
     * @type {object}
     * @memberof WritableCluster
     */
    custom_fields?: object;
    /**
     * 
     * @type {string}
     * @memberof WritableCluster
     */
    created?: string;
    /**
     * 
     * @type {string}
     * @memberof WritableCluster
     */
    last_updated?: string;
    /**
     * 
     * @type {number}
     * @memberof WritableCluster
     */
    device_count?: number;
    /**
     * 
     * @type {number}
     * @memberof WritableCluster
     */
    virtualmachine_count?: number;
}


