/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedCable } from './nested-cable';
import { NestedTag } from './nested-tag';

/**
 * 
 * @export
 * @interface WritablePowerOutlet
 */
export interface WritablePowerOutlet {
    /**
     * 
     * @type {number}
     * @memberof WritablePowerOutlet
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof WritablePowerOutlet
     */
    url?: string;
    /**
     * 
     * @type {number}
     * @memberof WritablePowerOutlet
     */
    device: number;
    /**
     * 
     * @type {string}
     * @memberof WritablePowerOutlet
     */
    name: string;
    /**
     * Physical label
     * @type {string}
     * @memberof WritablePowerOutlet
     */
    label?: string;
    /**
     * Physical port type
     * @type {string}
     * @memberof WritablePowerOutlet
     */
    type?: WritablePowerOutletTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof WritablePowerOutlet
     */
    power_port?: number | null;
    /**
     * Phase (for three-phase feeds)
     * @type {string}
     * @memberof WritablePowerOutlet
     */
    feed_leg?: WritablePowerOutletFeedLegEnum;
    /**
     * 
     * @type {string}
     * @memberof WritablePowerOutlet
     */
    description?: string;
    /**
     * 
     * @type {NestedCable}
     * @memberof WritablePowerOutlet
     */
    cable?: NestedCable;
    /**
     *  Return the appropriate serializer for the cable termination model. 
     * @type {{ [key: string]: string; }}
     * @memberof WritablePowerOutlet
     */
    cable_peer?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof WritablePowerOutlet
     */
    cable_peer_type?: string;
    /**
     *  Return the appropriate serializer for the type of connected object. 
     * @type {{ [key: string]: string; }}
     * @memberof WritablePowerOutlet
     */
    connected_endpoint?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof WritablePowerOutlet
     */
    connected_endpoint_type?: string;
    /**
     * 
     * @type {boolean}
     * @memberof WritablePowerOutlet
     */
    connected_endpoint_reachable?: boolean;
    /**
     * 
     * @type {Array<NestedTag>}
     * @memberof WritablePowerOutlet
     */
    tags?: Array<NestedTag>;
}

/**
    * @export
    * @enum {string}
    */
export enum WritablePowerOutletTypeEnum {
    Iec60320C5 = 'iec-60320-c5',
    Iec60320C7 = 'iec-60320-c7',
    Iec60320C13 = 'iec-60320-c13',
    Iec60320C15 = 'iec-60320-c15',
    Iec60320C19 = 'iec-60320-c19',
    Iec60309PNE4h = 'iec-60309-p-n-e-4h',
    Iec60309PNE6h = 'iec-60309-p-n-e-6h',
    Iec60309PNE9h = 'iec-60309-p-n-e-9h',
    Iec603092pE4h = 'iec-60309-2p-e-4h',
    Iec603092pE6h = 'iec-60309-2p-e-6h',
    Iec603092pE9h = 'iec-60309-2p-e-9h',
    Iec603093pE4h = 'iec-60309-3p-e-4h',
    Iec603093pE6h = 'iec-60309-3p-e-6h',
    Iec603093pE9h = 'iec-60309-3p-e-9h',
    Iec603093pNE4h = 'iec-60309-3p-n-e-4h',
    Iec603093pNE6h = 'iec-60309-3p-n-e-6h',
    Iec603093pNE9h = 'iec-60309-3p-n-e-9h',
    Nema115r = 'nema-1-15r',
    Nema515r = 'nema-5-15r',
    Nema520r = 'nema-5-20r',
    Nema530r = 'nema-5-30r',
    Nema550r = 'nema-5-50r',
    Nema615r = 'nema-6-15r',
    Nema620r = 'nema-6-20r',
    Nema630r = 'nema-6-30r',
    Nema650r = 'nema-6-50r',
    Nema1030r = 'nema-10-30r',
    Nema1050r = 'nema-10-50r',
    Nema1420r = 'nema-14-20r',
    Nema1430r = 'nema-14-30r',
    Nema1450r = 'nema-14-50r',
    Nema1460r = 'nema-14-60r',
    Nema1515r = 'nema-15-15r',
    Nema1520r = 'nema-15-20r',
    Nema1530r = 'nema-15-30r',
    Nema1550r = 'nema-15-50r',
    Nema1560r = 'nema-15-60r',
    NemaL115r = 'nema-l1-15r',
    NemaL515r = 'nema-l5-15r',
    NemaL520r = 'nema-l5-20r',
    NemaL530r = 'nema-l5-30r',
    NemaL550r = 'nema-l5-50r',
    NemaL615r = 'nema-l6-15r',
    NemaL620r = 'nema-l6-20r',
    NemaL630r = 'nema-l6-30r',
    NemaL650r = 'nema-l6-50r',
    NemaL1030r = 'nema-l10-30r',
    NemaL1420r = 'nema-l14-20r',
    NemaL1430r = 'nema-l14-30r',
    NemaL1450r = 'nema-l14-50r',
    NemaL1460r = 'nema-l14-60r',
    NemaL1520r = 'nema-l15-20r',
    NemaL1530r = 'nema-l15-30r',
    NemaL1550r = 'nema-l15-50r',
    NemaL1560r = 'nema-l15-60r',
    NemaL2120r = 'nema-l21-20r',
    NemaL2130r = 'nema-l21-30r',
    Cs6360C = 'CS6360C',
    Cs6364C = 'CS6364C',
    Cs8164C = 'CS8164C',
    Cs8264C = 'CS8264C',
    Cs8364C = 'CS8364C',
    Cs8464C = 'CS8464C',
    ItaE = 'ita-e',
    ItaF = 'ita-f',
    ItaG = 'ita-g',
    ItaH = 'ita-h',
    ItaI = 'ita-i',
    ItaJ = 'ita-j',
    ItaK = 'ita-k',
    ItaL = 'ita-l',
    ItaM = 'ita-m',
    ItaN = 'ita-n',
    ItaO = 'ita-o',
    UsbA = 'usb-a',
    UsbMicroB = 'usb-micro-b',
    UsbC = 'usb-c',
    HdotCx = 'hdot-cx'
}
/**
    * @export
    * @enum {string}
    */
export enum WritablePowerOutletFeedLegEnum {
    A = 'A',
    B = 'B',
    C = 'C'
}



