/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NestedTag } from './nested-tag';

/**
 * 
 * @export
 * @interface WritableDeviceType
 */
export interface WritableDeviceType {
    /**
     * 
     * @type {number}
     * @memberof WritableDeviceType
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof WritableDeviceType
     */
    url?: string;
    /**
     * 
     * @type {number}
     * @memberof WritableDeviceType
     */
    manufacturer: number;
    /**
     * 
     * @type {string}
     * @memberof WritableDeviceType
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof WritableDeviceType
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof WritableDeviceType
     */
    display_name?: string;
    /**
     * Discrete part number (optional)
     * @type {string}
     * @memberof WritableDeviceType
     */
    part_number?: string;
    /**
     * 
     * @type {number}
     * @memberof WritableDeviceType
     */
    u_height?: number;
    /**
     * Device consumes both front and rear rack faces
     * @type {boolean}
     * @memberof WritableDeviceType
     */
    is_full_depth?: boolean;
    /**
     * Parent devices house child devices in device bays. Leave blank if this device type is neither a parent nor a child.
     * @type {string}
     * @memberof WritableDeviceType
     */
    subdevice_role?: WritableDeviceTypeSubdeviceRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof WritableDeviceType
     */
    front_image?: string;
    /**
     * 
     * @type {string}
     * @memberof WritableDeviceType
     */
    rear_image?: string;
    /**
     * 
     * @type {string}
     * @memberof WritableDeviceType
     */
    comments?: string;
    /**
     * 
     * @type {Array<NestedTag>}
     * @memberof WritableDeviceType
     */
    tags?: Array<NestedTag>;
    /**
     * 
     * @type {object}
     * @memberof WritableDeviceType
     */
    custom_fields?: object;
    /**
     * 
     * @type {string}
     * @memberof WritableDeviceType
     */
    created?: string;
    /**
     * 
     * @type {string}
     * @memberof WritableDeviceType
     */
    last_updated?: string;
    /**
     * 
     * @type {number}
     * @memberof WritableDeviceType
     */
    device_count?: number;
}

/**
    * @export
    * @enum {string}
    */
export enum WritableDeviceTypeSubdeviceRoleEnum {
    Parent = 'parent',
    Child = 'child'
}



