/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WritableDeviceBayTemplate
 */
export interface WritableDeviceBayTemplate {
    /**
     * 
     * @type {number}
     * @memberof WritableDeviceBayTemplate
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof WritableDeviceBayTemplate
     */
    url?: string;
    /**
     * 
     * @type {number}
     * @memberof WritableDeviceBayTemplate
     */
    device_type: number;
    /**
     * 
     * @type {string}
     * @memberof WritableDeviceBayTemplate
     */
    name: string;
    /**
     * Physical label
     * @type {string}
     * @memberof WritableDeviceBayTemplate
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof WritableDeviceBayTemplate
     */
    description?: string;
}


