/* tslint:disable */
/* eslint-disable */
/**
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WritableRackGroup
 */
export interface WritableRackGroup {
    /**
     * 
     * @type {number}
     * @memberof WritableRackGroup
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof WritableRackGroup
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof WritableRackGroup
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof WritableRackGroup
     */
    slug: string;
    /**
     * 
     * @type {number}
     * @memberof WritableRackGroup
     */
    site: number;
    /**
     * 
     * @type {number}
     * @memberof WritableRackGroup
     */
    parent?: number | null;
    /**
     * 
     * @type {string}
     * @memberof WritableRackGroup
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof WritableRackGroup
     */
    rack_count?: number;
    /**
     * 
     * @type {number}
     * @memberof WritableRackGroup
     */
    _depth?: number;
}


